import { useEffect, useState, useRef } from "react";
import { Link, useParams, useLocation } from "wouter";
import {
  ArrowRight, Shield, AlertTriangle, Info, Lock,
  Share2, Check, Copy, Mail, ChevronDown, TrendingDown, Clock, CheckCircle2,
} from "lucide-react";
import { generateReport, type ReportResult, type Prediction } from "@/lib/report/engine";
import { SentinelReportSchema } from "@/lib/report/schema";
import AnimateIn from "@/components/AnimateIn";

// ── OG meta injection ────────────────────────────────────────────────────────

function setMeta(property: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[property="${property}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("property", property);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}
function setMetaName(name: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("name", name);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

function injectReportOG(result: ReportResult) {
  const title = `${result.system.model} — ${result.grade} (${result.overall}/100) · Sentinel`;
  const desc = `Hardware health report: ${result.components.map((c) => `${c.name} ${c.score}/100`).join(" · ")}. Generated by Sentinel.`;
  document.title = title;
  setMeta("og:title", title);
  setMeta("og:description", desc);
  setMeta("og:type", "article");
  setMetaName("twitter:title", title);
  setMetaName("twitter:description", desc);
}

// ── Score ring ───────────────────────────────────────────────────────────────

const STATUS_STYLES = {
  healthy:   { bar: "bg-green-500",  badge: "text-green-400 border-green-400/20 bg-green-400/5"  },
  watch:     { bar: "bg-cyan-400",   badge: "text-cyan-400 border-cyan-400/20 bg-cyan-400/5"     },
  attention: { bar: "bg-amber-400",  badge: "text-amber-400 border-amber-400/20 bg-amber-400/5"  },
  critical:  { bar: "bg-red-400",    badge: "text-red-400 border-red-400/20 bg-red-400/5"        },
};

const URGENCY_STYLES = {
  critical: { border: "border-l-red-400",     badge: "text-red-400 bg-red-400/8 border-red-400/20"     },
  warning:  { border: "border-l-amber-400",   badge: "text-amber-400 bg-amber-400/8 border-amber-400/20" },
  info:     { border: "border-l-cyan-400/40", badge: "text-cyan-400 bg-cyan-400/8 border-cyan-400/20"   },
};

function ScoreRing({ score }: { score: number }) {
  const r = 40;
  const circ = 2 * Math.PI * r;
  const dash = (score / 100) * circ;
  const color = score >= 80 ? "#22d3ee" : score >= 60 ? "#f59e0b" : "#f87171";
  return (
    <svg width="100" height="100" viewBox="0 0 100 100" className="rotate-[-90deg]">
      <circle cx="50" cy="50" r={r} fill="none" stroke="currentColor" strokeWidth="8" className="text-border/30" />
      <circle cx="50" cy="50" r={r} fill="none" stroke={color} strokeWidth="8"
        strokeDasharray={`${dash} ${circ}`} strokeLinecap="round"
        style={{ transition: "stroke-dasharray 1s ease" }} />
    </svg>
  );
}

// ── Share row ─────────────────────────────────────────────────────────────────

function ShareRow({ id, isLocal }: { id: string, isLocal?: boolean }) {
  const [copied, setCopied] = useState(false);
  const url = `${window.location.origin}/r/${id}`;
  const copy = () => {
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };
  return (
    <div className="surface-card rounded-xl p-5 flex items-center justify-between flex-wrap gap-4">
      <div className={`flex items-center gap-2 text-sm text-muted-foreground ${isLocal ? 'opacity-40 blur-[2px] select-none pointer-events-none' : ''}`}>
        <Share2 className="w-4 h-4 text-primary/60" />
        <span className="font-mono text-xs text-muted-foreground/60 truncate max-w-[220px]">{url}</span>
      </div>
      <button
        onClick={copy}
        disabled={isLocal}
        title={isLocal ? "Save to server to get a shareable link." : undefined}
        className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-border/60 text-foreground transition-all ${isLocal ? 'opacity-40 blur-[1px] cursor-not-allowed' : 'hover:border-primary/60 hover:text-primary'}`}
      >
        {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
        {copied ? "Copied!" : "Copy link"}
      </button>
    </div>
  );
}

// ── Claim panel ───────────────────────────────────────────────────────────────

type ClaimState = "idle" | "open" | "submitting" | "done" | "error";

function ClaimPanel({ id }: { id: string }) {
  const claimToken = typeof window !== "undefined"
    ? localStorage.getItem(`sentinel_claim_${id}`) ?? ""
    : "";

  const [state, setState] = useState<ClaimState>("idle");
  const [email, setEmail] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  // No claimToken = not the owner; don't show claim UI
  if (!claimToken) return null;

  if (state === "done") {
    return (
      <div className="surface-card rounded-xl p-5 flex items-center gap-3 border border-green-400/20">
        <Check className="w-4 h-4 text-green-400 shrink-0" />
        <div className="text-sm">
          <span className="text-foreground font-medium">Report saved.</span>{" "}
          <span className="text-muted-foreground">We'll email you when predictive alerts land.</span>
        </div>
      </div>
    );
  }

  if (state !== "open" && state !== "submitting") {
    return (
      <button
        onClick={() => { setState("open"); setTimeout(() => inputRef.current?.focus(), 50); }}
        className="w-full surface-card rounded-xl p-5 flex items-center justify-between gap-4 hover:border-primary/40 transition-all border border-border/60 text-left"
      >
        <div className="flex items-center gap-3">
          <Mail className="w-4 h-4 text-primary/60 shrink-0" />
          <div>
            <div className="text-sm font-medium text-foreground">Save this report to your account</div>
            <div className="text-xs text-muted-foreground mt-0.5">Get email alerts when predictive insights are ready.</div>
          </div>
        </div>
        <ChevronDown className="w-4 h-4 text-muted-foreground/40 shrink-0" />
      </button>
    );
  }

  const submit = async () => {
    if (!email.includes("@")) { setErrorMsg("Enter a valid email address."); return; }
    setState("submitting");
    setErrorMsg("");
    try {
      const res = await fetch(`/api/reports/${id}/claim`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ claimToken, email }),
      });
      if (res.ok) {
        setState("done");
      } else {
        const body = await res.json() as { error?: string };
        setErrorMsg(body.error ?? "Something went wrong.");
        setState("open");
      }
    } catch {
      setErrorMsg("Network error. Try again.");
      setState("open");
    }
  };

  return (
    <div className="surface-card rounded-xl p-5 border border-primary/20">
      <div className="flex items-center gap-2 mb-4">
        <Mail className="w-4 h-4 text-primary/60" />
        <span className="text-sm font-medium">Save this report</span>
      </div>
      <p className="text-xs text-muted-foreground mb-4 leading-relaxed">
        Enter your email and we'll link this report to your account — accessible from any device — and notify you when predictive health alerts are ready.
      </p>
      <div className="flex gap-2">
        <input
          ref={inputRef}
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && submit()}
          placeholder="you@example.com"
          disabled={state === "submitting"}
          className="flex-1 bg-background border border-border/60 rounded-lg px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/40 focus:outline-none focus:border-primary/60 disabled:opacity-50 transition-colors"
        />
        <button
          onClick={submit}
          disabled={state === "submitting" || !email}
          className="px-4 py-2 rounded-lg text-sm font-semibold text-background bg-primary hover:bg-primary/90 disabled:opacity-40 disabled:cursor-not-allowed transition-all shrink-0"
        >
          {state === "submitting" ? "Saving…" : "Save"}
        </button>
      </div>
      {errorMsg && <p className="text-xs text-red-400 mt-2">{errorMsg}</p>}
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function Report() {
  const params = useParams<{ id: string }>();
  const [result, setResult] = useState<ReportResult | null>(null);
  const [habitScore, setHabitScore] = useState<number | null>(null);
  const [combinedScoreVal, setCombinedScoreVal] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loadedFrom, setLoadedFrom] = useState<"server" | "local" | null>(null);
  const [, navigate] = useLocation();

  useEffect(() => {
    const id = params?.id;
    if (!id) { setError("No report ID provided."); return; }

    fetch(`/api/reports/${id}`)
      .then(async (res) => {
        if (res.ok) {
          const body = await res.json() as { result: ReportResult; habitScore: number | null; combinedScore: number | null };
          setResult(body.result);
          setHabitScore(body.habitScore);
          setCombinedScoreVal(body.combinedScore);
          setLoadedFrom("server");
          injectReportOG(body.result);
          return;
        }
        if (res.status === 404) {
          loadFromLocalStorage(id);
          // Opportunistic upload for legacy local IDs
          const stored = localStorage.getItem(`sentinel_report_${id}`);
          if (stored) {
            try {
              fetch("/api/reports", {
                method: "POST",
                headers: { "Content-Type": "application/json", "Idempotency-Key": `legacy-${id}` },
                body: JSON.stringify({ rawJson: JSON.parse(stored), legacy: true }),
              })
                .then(async (upRes) => {
                  if (upRes.ok) {
                    const { id: newId } = await upRes.json() as { id: string };
                    navigate(`/r/${newId}`);
                  }
                })
                .catch(() => {});
            } catch {}
          }
          return;
        }
        loadFromLocalStorage(id);
      })
      .catch(() => loadFromLocalStorage(id));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [params?.id]);

  function loadFromLocalStorage(id: string) {
    const stored = localStorage.getItem(`sentinel_report_${id}`);
    if (!stored) {
      setError("Report not found. Reports are stored locally — this link only works on the device that generated it.");
      return;
    }
    try {
      const raw = JSON.parse(stored);
      const parsed = SentinelReportSchema.safeParse(raw);
      if (!parsed.success) { setError("Report data is corrupted or outdated."); return; }
      const r = generateReport(parsed.data);
      setResult(r);
      setLoadedFrom("local");
      injectReportOG(r);
    } catch {
      setError("Could not load report data.");
    }
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center px-6">
        <div className="max-w-md text-center">
          <Shield className="w-10 h-10 text-muted-foreground/30 mx-auto mb-4" />
          <h2 className="text-lg font-semibold mb-2">Report not found</h2>
          <p className="text-sm text-muted-foreground mb-6 leading-relaxed">{error}</p>
          <Link href="/health-test" className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-background bg-primary glow-cyan">
            Generate a new report <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-sm text-muted-foreground font-mono animate-pulse">Loading report…</div>
      </div>
    );
  }

  const id = params?.id ?? "";
  const urgencyOrder = { critical: 0, warning: 1, info: 2 } as const;
  const publicFindings = result.findings.filter((f) => !f.pro).sort((a, b) => urgencyOrder[a.urgency] - urgencyOrder[b.urgency]);
  const proFindings    = result.findings.filter((f) => f.pro);
  const genDate = new Date(result.generatedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  return (
    <div className="min-h-screen bg-background text-foreground">
      {loadedFrom === "local" && (
        <div className="w-full bg-amber-500 text-amber-950 px-6 py-4 flex items-center justify-center gap-3 shadow-md z-50 relative">
          <AlertTriangle className="w-5 h-5 shrink-0" />
          <p className="text-sm font-bold">
            This report was scored offline and has not been verified by Sentinel servers. Scores may differ from the server-computed result.
          </p>
        </div>
      )}

      {/* Report header */}
      <div className="border-b border-border/60 bg-card/20 px-6 py-5">
        <AnimateIn>
          <div className="max-w-3xl mx-auto flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center">
                <Shield className="w-4 h-4 text-primary" />
              </div>
              <div>
                <div className="text-xs font-mono text-muted-foreground/60 uppercase tracking-wide">Sentinel Hardware Report</div>
                <div className="text-sm font-semibold">{result.system.model}</div>
              </div>
            </div>
            <div className="flex items-center gap-3">
              {loadedFrom === "server" && (
                <span className="text-xs font-mono text-green-400/60 border border-green-400/20 bg-green-400/5 px-2 py-0.5 rounded-full">
                  synced
                </span>
              )}
              <div className="text-xs font-mono text-muted-foreground/50">{genDate}</div>
            </div>
          </div>
        </AnimateIn>
      </div>

      <div className="px-6 py-12">
        <div className="max-w-3xl mx-auto space-y-8">

          {/* Overall score */}
          <AnimateIn>
            <div className="surface-card rounded-2xl p-8">
              <div className="flex items-center gap-8 flex-wrap">
                <div className="relative shrink-0">
                  <ScoreRing score={combinedScoreVal ?? result.overall} />
                  <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <div className="text-2xl font-bold tabular-nums">{combinedScoreVal ?? result.overall}</div>
                    <div className="text-xs text-muted-foreground">/100</div>
                  </div>
                </div>
                <div className="flex-1">
                  <div className="text-2xl font-bold mb-1 flex items-center gap-3">
                    {result.grade} — {result.gradeLabel}
                    {loadedFrom === "local" && (
                      <span className="text-xs font-mono text-amber-500 border border-amber-500/30 bg-amber-500/10 px-2 py-0.5 rounded-full font-normal tracking-wide flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" /> unverified
                      </span>
                    )}
                  </div>
                  {combinedScoreVal !== null && (
                    <div className="flex items-center gap-3 mb-3 text-xs font-mono">
                      <span className="text-muted-foreground/60">Hardware</span>
                      <span className="text-foreground">{result.overall}</span>
                      <span className="text-muted-foreground/40">+</span>
                      <span className="text-muted-foreground/60">Habits</span>
                      <span className="text-accent">{habitScore}</span>
                      <span className="text-muted-foreground/40">→</span>
                      <span className="text-primary font-semibold">Combined {combinedScoreVal}</span>
                    </div>
                  )}
                  <div className="text-sm text-muted-foreground mb-4 leading-relaxed">
                    {(combinedScoreVal ?? result.overall) >= 80
                      ? "Your hardware is in good shape. A few items to watch."
                      : (combinedScoreVal ?? result.overall) >= 60
                      ? "Some components need attention. Review the findings below."
                      : "Multiple components are degraded. Prioritise the critical findings."}
                  </div>
                  <div className="flex flex-wrap gap-2 text-xs">
                    <span className="text-red-400/80 bg-red-400/5 border border-red-400/20 px-2 py-0.5 rounded-full font-mono">
                      {publicFindings.filter((f) => f.urgency === "critical").length} critical
                    </span>
                    <span className="text-amber-400/80 bg-amber-400/5 border border-amber-400/20 px-2 py-0.5 rounded-full font-mono">
                      {publicFindings.filter((f) => f.urgency === "warning").length} warnings
                    </span>
                    <span className="text-cyan-400/80 bg-cyan-400/5 border border-cyan-400/20 px-2 py-0.5 rounded-full font-mono">
                      {publicFindings.filter((f) => f.urgency === "info").length} healthy
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </AnimateIn>

          {/* ── Data Quality Transparency Banners ───────────────────────── */}
          {result.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0 && (
            <AnimateIn delay={0.04}>
              <div className="space-y-3">
                {result.dataQuality.structuredWarnings.map((w, i) => {
                  const isHigh = w.severity === "high";
                  return (
                    <div
                      key={i}
                      className={`rounded-xl border overflow-hidden ${
                        isHigh
                          ? "border-amber-500/40 bg-amber-500/8"
                          : "border-amber-500/20 bg-amber-500/5"
                      }`}
                    >
                      {/* Banner header */}
                      <div className={`px-5 py-3 flex items-center gap-3 ${
                        isHigh ? "bg-amber-500/15 border-b border-amber-500/20" : "border-b border-amber-500/10"
                      }`}>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                          isHigh ? "bg-amber-500/20" : "bg-amber-500/10"
                        }`}>
                          <AlertTriangle className={`w-4 h-4 ${isHigh ? "text-amber-400" : "text-amber-500/70"}`} />
                        </div>
                        <div className="flex-1">
                          <h3 className={`text-sm font-bold ${isHigh ? "text-amber-400" : "text-amber-500/80"}`}>
                            {w.title}
                          </h3>
                          {w.excludedFromScoring && (
                            <span className="text-xs font-mono text-amber-500/50 mt-0.5 block">
                              EXCLUDED FROM OVERALL SCORE
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Banner body */}
                      <div className="px-5 py-4 space-y-3">
                        <p className="text-sm text-muted-foreground leading-relaxed">{w.detail}</p>
                        {w.oemComparison && (
                          <div className="rounded-lg bg-background/60 border border-border/40 px-4 py-3">
                            <p className="text-xs font-mono text-muted-foreground/50 uppercase tracking-wide mb-1.5">
                              vs. OEM tools
                            </p>
                            <p className="text-xs text-muted-foreground/80 leading-relaxed">{w.oemComparison}</p>
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Legacy fallback: plain-text data quality warnings (only if no structured ones) */}
          {(!result.dataQuality?.structuredWarnings || result.dataQuality.structuredWarnings.length === 0) &&
            result.dataQuality?.warnings && result.dataQuality.warnings.length > 0 && (
            <AnimateIn delay={0.04}>
              <div className="surface-card rounded-xl p-5 border border-amber-500/20 bg-amber-500/5">
                <div className="flex items-center gap-3 mb-3">
                  <Info className="w-4 h-4 text-amber-500" />
                  <h2 className="text-sm font-bold text-amber-500 uppercase tracking-wider">Data Collection Notes</h2>
                </div>
                <ul className="space-y-2">
                  {result.dataQuality.warnings.map((w: string, i: number) => (
                    <li key={i} className="text-sm text-amber-500/80 list-disc list-inside">{w}</li>
                  ))}
                </ul>
              </div>
            </AnimateIn>
          )}

          {/* Component breakdown */}
          <AnimateIn delay={0.05}>
            <div className="surface-card rounded-2xl p-7">
              <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest mb-5">Component breakdown</h2>
              <div className="space-y-4">
                {result.components.map((c) => {
                  const s = STATUS_STYLES[c.status];
                  return (
                    <div key={c.name}>
                      <div className="flex items-center justify-between mb-1.5">
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-medium text-foreground">{c.name}</span>
                          <span className={`text-xs px-1.5 py-0.5 rounded border ${s.badge} font-mono`}>{c.status}</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <span className="text-xs text-muted-foreground font-mono">{c.detail}</span>
                          <span className="text-sm font-bold font-mono tabular-nums w-8 text-right">{c.score}</span>
                        </div>
                      </div>
                      <div className="h-1.5 bg-border/30 rounded-full overflow-hidden">
                        <div className={`h-full rounded-full ${s.bar} transition-all duration-700`} style={{ width: `${c.score}%` }} />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </AnimateIn>

          {/* ── Health Forecast Timeline ────────────────────────────────────── */}
          {result.predictions && result.predictions.length > 0 && (
            <AnimateIn delay={0.06}>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Health Forecast Timeline</h2>
                  <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-primary/10 border border-primary/30 text-primary flex items-center gap-1">
                    <Clock className="w-3 h-3" /> FORECAST
                  </span>
                </div>
                <p className="text-xs text-muted-foreground/50 leading-relaxed -mt-1 mb-1">
                  How long before each component becomes a problem — based on current readings and degradation curves.
                </p>
                {result.predictions.map((pred, i) => {
                  const severityStyles = {
                    stable: {
                      border: "border-l-green-400",
                      icon: <CheckCircle2 className="w-4 h-4 text-green-400" />,
                      badge: "text-green-400 bg-green-400/8 border-green-400/20",
                      badgeLabel: "Stable",
                      glow: "bg-green-400",
                    },
                    declining: {
                      border: "border-l-amber-400",
                      icon: <TrendingDown className="w-4 h-4 text-amber-400" />,
                      badge: "text-amber-400 bg-amber-400/8 border-amber-400/20",
                      badgeLabel: "Declining",
                      glow: "bg-amber-400",
                    },
                    urgent: {
                      border: "border-l-red-400",
                      icon: <AlertTriangle className="w-4 h-4 text-red-400" />,
                      badge: "text-red-400 bg-red-400/8 border-red-400/20",
                      badgeLabel: "Urgent",
                      glow: "bg-red-400",
                    },
                  };
                  const s = severityStyles[pred.severity];
                  return (
                    <div key={i} className={`surface-card rounded-xl p-5 border-l-2 ${s.border}`}>
                      <div className="flex items-start justify-between gap-4 mb-3">
                        <div className="flex items-center gap-3">
                          {s.icon}
                          <div>
                            <div className="text-sm font-semibold text-foreground">{pred.component}</div>
                            <div className="text-xs font-mono text-muted-foreground/50 mt-0.5">{pred.currentValue}</div>
                          </div>
                        </div>
                        <span className={`text-xs font-mono px-2 py-0.5 rounded-full border shrink-0 ${s.badge}`}>
                          {s.badgeLabel}
                        </span>
                      </div>
                      {/* Timeline bar */}
                      <div className="rounded-lg bg-muted/10 border border-border/30 px-4 py-3 mb-3">
                        <div className="flex items-center gap-2 mb-1">
                          <Clock className="w-3 h-3 text-muted-foreground/40" />
                          <span className="text-xs font-mono text-muted-foreground/50 uppercase tracking-wide">Projected Timeline</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className={`w-2 h-2 rounded-full ${s.glow} animate-glow-pulse shrink-0`} />
                          <span className="text-sm font-medium text-foreground">{pred.projectedTimeline}</span>
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">{pred.insight}</p>
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Public findings */}
          {publicFindings.length > 0 && (
            <AnimateIn delay={0.07}>
              <div className="space-y-3">
                <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Findings</h2>
                {publicFindings.map((f, i) => {
                  const style = URGENCY_STYLES[f.urgency];
                  return (
                    <div key={i} className={`surface-card rounded-xl p-5 border-l-2 ${style.border}`}>
                      <div className="flex items-start gap-3 mb-2">
                        <span className={`text-xs font-mono px-1.5 py-0.5 rounded border uppercase ${style.badge} shrink-0 mt-0.5`}>{f.urgency}</span>
                        <div>
                          <div className="text-xs font-mono text-muted-foreground/50 mb-0.5">{f.component}</div>
                          <div className="text-sm font-semibold text-foreground">{f.title}</div>
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">{f.body}</p>
                      {f.oemContext && (
                        <div className="mt-3 rounded-lg bg-primary/5 border border-primary/15 px-4 py-3">
                          <p className="text-xs font-mono text-primary/60 uppercase tracking-wide mb-1.5 flex items-center gap-1.5">
                            <Shield className="w-3 h-3" />
                            Why OEM tools miss this
                          </p>
                          <p className="text-xs text-muted-foreground/80 leading-relaxed">{f.oemContext}</p>
                          {f.caseStudyId && (
                            <Link
                              href={`/oem-failures#${f.caseStudyId}`}
                              className="mt-2 inline-flex items-center gap-1 text-xs text-primary/70 hover:text-primary transition-colors"
                            >
                              See the real-world case study →
                            </Link>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Pro findings (blurred) */}
          {proFindings.length > 0 && (
            <AnimateIn delay={0.08}>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Diagnostic findings</h2>
                  <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-accent/10 border border-accent/30 text-accent">PRO</span>
                </div>
                {proFindings.map((f, i) => (
                  <div key={i} className="surface-card rounded-xl p-5 border border-accent/20 relative overflow-hidden">
                    <div className="absolute inset-0 backdrop-blur-sm bg-background/60 z-10 flex items-center justify-center rounded-xl">
                      <div className="text-center px-6">
                        <Lock className="w-5 h-5 text-accent mx-auto mb-2" />
                        <div className="text-sm font-semibold text-foreground mb-1">Pro finding</div>
                        <div className="text-xs text-muted-foreground mb-3">Pro diagnostic findings unlock with early access.</div>
                        <Link href="/waitlist" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold text-background bg-accent hover:bg-accent/90 transition-all">
                          Get early access <ArrowRight className="w-3 h-3" />
                        </Link>
                      </div>
                    </div>
                    <div className="opacity-20 select-none pointer-events-none" aria-hidden>
                      <div className="text-xs font-mono text-muted-foreground/50 mb-1">{f.component}</div>
                      <div className="text-sm font-semibold mb-2">{f.title}</div>
                      <p className="text-sm text-muted-foreground">{f.body}</p>
                    </div>
                  </div>
                ))}
              </div>
            </AnimateIn>
          )}

          {/* Claim panel (only shown when user owns the report) */}
          <AnimateIn delay={0.06}>
            <ClaimPanel id={id} />
          </AnimateIn>

          {/* Share row */}
          <AnimateIn delay={0.07}>
            <ShareRow id={id} isLocal={loadedFrom === "local"} />
          </AnimateIn>

          {/* Footer */}
          <AnimateIn delay={0.08}>
            <div className="surface-card rounded-xl p-5 space-y-3">
              <div className="flex items-center justify-between flex-wrap gap-4">
                <div className="text-xs text-muted-foreground/60 leading-relaxed max-w-sm">
                  {loadedFrom === "server"
                    ? "This report is stored on Sentinel's servers and accessible from any device via the link above."
                    : "This report was generated from your device's hardware telemetry."}
                </div>
                <Link
                  href="/health-test"
                  className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-xs font-semibold border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all"
                >
                  Run another scan <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
              <div className="border-t border-border/30 pt-3 flex items-center justify-between flex-wrap gap-2">
                <span className="text-xs font-mono text-muted-foreground/40">
                  Algorithm v{result.algoVersion} · {genDate}
                </span>
                <Link
                  href="/changelog"
                  className="text-xs text-primary/60 hover:text-primary transition-colors flex items-center gap-1"
                >
                  Scoring methodology & changelog <ArrowRight className="w-3 h-3" />
                </Link>
              </div>
            </div>
          </AnimateIn>

        </div>
      </div>
    </div>
  );
}
