import React, { useEffect, useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ResponsiveContainer, ComposedChart, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ReferenceArea } from "recharts";

import { Link, useParams, useLocation } from "wouter";
import {
  ArrowRight, Shield, AlertTriangle, Info, Lock,
  Share2, Check, Copy, Mail, ChevronDown, TrendingDown, Clock, CheckCircle2, Printer,
} from "lucide-react";
import { generateReport, type ReportResult, type Prediction } from "@/lib/report/engine";
import { SentinelReportSchema } from "@/lib/report/schema";
import AnimateIn from "@/components/AnimateIn";
import AdvancedDiagnostics from "@/components/AdvancedDiagnostics";

// ── OG meta injection ────────────────────────────────────────────────────────

/**
 * Dynamically injects open graph (OG) metadata properties into the document head.
 * 
 * @param property The meta property name.
 * @param content The value content of the property.
 */
function setMeta(property: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[property="${property}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("property", property);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

/**
 * Dynamically updates or creates a standard name-based meta tag in the head.
 * 
 * @param name The meta tag name attribute.
 * @param content The content value to inject.
 */
function setMetaName(name: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("name", name);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

function injectReportOG(result: ReportResult) {
  const title = `${result.system.model} — ${result.grade} (${result.overall}/100) · Sentinel`;
  const desc = `Hardware health report: ${result.components.map((c) => `${c.name} ${c.score}/100`).join(" · ")}. Generated by Sentinel.`;
  document.title = title;
  setMeta("og:title", title);
  setMeta("og:description", desc);
  setMeta("og:type", "article");
  setMetaName("twitter:title", title);
  setMetaName("twitter:description", desc);
}

// ── Score ring ───────────────────────────────────────────────────────────────

const STATUS_STYLES = {
  healthy:   { bar: "bg-green-500",  badge: "text-green-400 border-green-400/20 bg-green-400/5"  },
  watch:     { bar: "bg-cyan-400",   badge: "text-cyan-400 border-cyan-400/20 bg-cyan-400/5"     },
  attention: { bar: "bg-amber-400",  badge: "text-amber-400 border-amber-400/20 bg-amber-400/5"  },
  critical:  { bar: "bg-red-400",    badge: "text-red-400 border-red-400/20 bg-red-400/5"        },
};

const URGENCY_STYLES = {
  critical: { border: "border-l-red-400",     badge: "text-red-400 bg-red-400/8 border-red-400/20"     },
  warning:  { border: "border-l-amber-400",   badge: "text-amber-400 bg-amber-400/8 border-amber-400/20" },
  info:     { border: "border-l-cyan-400/40", badge: "text-cyan-400 bg-cyan-400/8 border-cyan-400/20"   },
};

/**
 * Renders an interactive circular health score indicator ring with standard Apple-style
 * easing transitions.
 * 
 * @param score Overall computed hardware score.
 */
function ScoreRing({ score, size = 148 }: { score: number; size?: number }) {
  const strokeW = 11;
  const r = (size - strokeW) / 2;
  const circ = 2 * Math.PI * r;
  const color = score >= 80 ? "#22d3ee" : score >= 60 ? "#f59e0b" : "#f87171";
  const glowColor = score >= 80 ? "#06b6d4" : score >= 60 ? "#d97706" : "#ef4444";

  const [displayed, setDisplayed] = React.useState(0);

  React.useEffect(() => {
    import("framer-motion").then(({ animate }) => {
      animate(0, score, {
        duration: 1.0,
        ease: [0.25, 0.1, 0.25, 1],
        onUpdate: (val) => setDisplayed(Math.round(val)),
      });
    });
  }, [score]);

  const dash = (displayed / 100) * circ;

  return (
    <div className="relative shrink-0" style={{ width: size, height: size }}>
      {/* Ambient glow behind ring */}
      <div
        className="absolute inset-0 rounded-full"
        style={{ background: `radial-gradient(circle, ${glowColor}18 0%, transparent 70%)` }}
      />
      <svg
        width={size}
        height={size}
        viewBox={`0 0 ${size} ${size}`}
        className="rotate-[-90deg] absolute inset-0 z-0"
      >
        {/* Track */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke="currentColor"
          strokeWidth={strokeW}
          className="text-border/30"
        />
        {/* Glow arc (avoids Safari drop-shadow transform drift bug) */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke={color}
          strokeWidth={strokeW}
          strokeDasharray={`${dash} ${circ}`}
          strokeLinecap="round"
          style={{
            filter: "blur(6px)",
            opacity: 0.6,
            transition: "stroke-dasharray 0.05s linear",
          }}
        />
        {/* Progress arc */}
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke={color}
          strokeWidth={strokeW}
          strokeDasharray={`${dash} ${circ}`}
          strokeLinecap="round"
          style={{
            transition: "stroke-dasharray 0.05s linear",
          }}
        />
      </svg>
      {/* Score text — centred inside ring (only rendered here, NOT duplicated outside) */}
      <div className="absolute inset-0 flex flex-col items-center justify-center z-10" style={{ transform: 'translateZ(0)' }}>
        <div
          className="text-4xl font-black tabular-nums leading-none"
          style={{ color, textShadow: `0 0 20px ${color}60` }}
        >
          {displayed}
        </div>
        <div className="text-[11px] font-mono text-muted-foreground/50 mt-0.5">/100</div>
      </div>
    </div>
  );
}

// ── Share + PDF panel ─────────────────────────────────────────────────────────

function SharePanel({ id, isLocal }: { id: string; isLocal?: boolean }) {
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedDirect, setCopiedDirect] = useState(false);

  const directUrl = `${window.location.origin}/r/${id}`;

  const generateShareLink = async () => {
    const claimToken = localStorage.getItem(`sentinel_claim_${id}`) ?? "";
    if (!claimToken) return;

    setGenerating(true);
    try {
      const res = await fetch(`/api/reports/${id}/share`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ claimToken }),
      });
      if (res.ok) {
        const { shareToken } = await res.json() as { shareToken: string };
        setShareUrl(`${window.location.origin}/s/${shareToken}`);
      }
    } catch {
      // silently fail — the direct link is still available
    } finally {
      setGenerating(false);
    }
  };

  const copyShareUrl = () => {
    const url = shareUrl ?? directUrl;
    navigator.clipboard.writeText(url).then(() => {
      if (shareUrl) {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } else {
        setCopiedDirect(true);
        setTimeout(() => setCopiedDirect(false), 2000);
      }
    });
  };

  const hasClaimToken = typeof window !== "undefined" && !!localStorage.getItem(`sentinel_claim_${id}`);

  return (
    <div className="surface-card rounded-xl p-5 space-y-4 print:hidden">
      <div className="flex items-center gap-2 mb-1">
        <Share2 className="w-4 h-4 text-primary/60" />
        <span className="text-sm font-medium text-foreground">Share this report</span>
      </div>

      {/* Public share link (stripped of PII) */}
      {hasClaimToken && !isLocal && (
        <div className="space-y-2">
          {!shareUrl ? (
            <button
              onClick={generateShareLink}
              disabled={generating}
              className="w-full text-left px-4 py-3 rounded-lg border border-primary/20 bg-primary/5 hover:bg-primary/8 transition-all group"
            >
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-sm font-medium text-foreground">
                    {generating ? "Generating…" : "Generate read-only link"}
                  </div>
                  <div className="text-xs text-muted-foreground/60 mt-0.5">
                    Creates a public link with just the score, components, and findings — no email or personal info.
                    Send it to a repair shop, a friend, or post it in a forum.
                  </div>
                </div>
                <ArrowRight className="w-4 h-4 text-primary/40 group-hover:text-primary transition-colors shrink-0 ml-3" />
              </div>
            </button>
          ) : (
            <div className="rounded-lg border border-green-400/20 bg-green-400/5 px-4 py-3">
              <div className="flex items-center gap-2 mb-1.5">
                <Check className="w-3.5 h-3.5 text-green-400" />
                <span className="text-xs font-medium text-green-400">Public link ready</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs text-muted-foreground/60 truncate flex-1">{shareUrl}</span>
                <button
                  onClick={copyShareUrl}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all shrink-0"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
              <p className="text-[10px] text-muted-foreground/40 mt-2">This link shows only: score, components, findings, algorithm version. No email, no raw data.</p>
            </div>
          )}
        </div>
      )}

      {/* Direct link (fallback) */}
      <div className={`flex items-center justify-between flex-wrap gap-3 ${isLocal ? "opacity-40 blur-[2px] select-none pointer-events-none" : ""}`}>
        <span className="font-mono text-xs text-muted-foreground/60 truncate max-w-[220px]">{directUrl}</span>
        <button
          onClick={() => {
            navigator.clipboard.writeText(directUrl).then(() => {
              setCopiedDirect(true);
              setTimeout(() => setCopiedDirect(false), 2000);
            });
          }}
          disabled={isLocal}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all"
        >
          {copiedDirect ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
          {copiedDirect ? "Copied!" : "Copy direct link"}
        </button>
      </div>

      {/* Print / PDF */}
      <div className="border-t border-border/30 pt-3">
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all w-full justify-center sm:w-auto"
        >
          <Printer className="w-3.5 h-3.5" />
          Print / Export as PDF
        </button>
        <p className="text-[10px] text-muted-foreground/40 mt-1.5">Uses your browser's built-in Print dialog. Choose "Save as PDF" to download.</p>
      </div>
    </div>
  );
}

// ── Claim panel ───────────────────────────────────────────────────────────────

type ClaimState = "idle" | "open" | "submitting" | "done" | "error";

function ClaimPanel({ id }: { id: string }) {
  const claimToken = typeof window !== "undefined"
    ? localStorage.getItem(`sentinel_claim_${id}`) ?? ""
    : "";

  const [state, setState] = useState<ClaimState>("idle");
  const [email, setEmail] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  // No claimToken = not the owner; don't show claim UI
  if (!claimToken) return null;

  if (state === "done") {
    return (
      <div className="surface-card rounded-xl p-5 flex items-center gap-3 border border-green-400/20">
        <Check className="w-4 h-4 text-green-400 shrink-0" />
        <div className="text-sm">
          <span className="text-foreground font-medium">Report saved.</span>{" "}
          <span className="text-muted-foreground">We'll email you when predictive alerts land.</span>
        </div>
      </div>
    );
  }

  if (state !== "open" && state !== "submitting") {
    return (
      <button
        onClick={() => { setState("open"); setTimeout(() => inputRef.current?.focus(), 50); }}
        className="w-full surface-card rounded-xl p-5 flex items-center justify-between gap-4 hover:border-primary/40 transition-all border border-border/60 text-left"
      >
        <div className="flex items-center gap-3">
          <Mail className="w-4 h-4 text-primary/60 shrink-0" />
          <div>
            <div className="text-sm font-medium text-foreground">Save this report to your account</div>
            <div className="text-xs text-muted-foreground mt-0.5">Get email alerts when predictive insights are ready.</div>
          </div>
        </div>
        <ChevronDown className="w-4 h-4 text-muted-foreground/40 shrink-0" />
      </button>
    );
  }

  const submit = async () => {
    if (!email.includes("@")) { setErrorMsg("Enter a valid email address."); return; }
    setState("submitting");
    setErrorMsg("");
    try {
      const res = await fetch(`/api/reports/${id}/claim`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ claimToken, email }),
      });
      if (res.ok) {
        setState("done");
      } else {
        const body = await res.json() as { error?: string };
        setErrorMsg(body.error ?? "Something went wrong.");
        setState("open");
      }
    } catch {
      setErrorMsg("Network error. Try again.");
      setState("open");
    }
  };

  return (
    <div className="surface-card rounded-xl p-5 border border-primary/20">
      <div className="flex items-center gap-2 mb-4">
        <Mail className="w-4 h-4 text-primary/60" />
        <span className="text-sm font-medium">Save this report</span>
      </div>
      <p className="text-xs text-muted-foreground mb-4 leading-relaxed">
        Enter your email and we'll link this report to your account — accessible from any device — and notify you when predictive health alerts are ready.
      </p>
      <div className="flex gap-2">
        <input
          ref={inputRef}
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && submit()}
          placeholder="you@example.com"
          disabled={state === "submitting"}
          className="flex-1 bg-background border border-border/60 rounded-lg px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/40 focus:outline-none focus:border-primary/60 disabled:opacity-50 transition-colors"
        />
        <button
          onClick={submit}
          disabled={state === "submitting" || !email}
          className="px-4 py-2 rounded-lg text-sm font-semibold text-background bg-primary hover:bg-primary/90 disabled:opacity-40 disabled:cursor-not-allowed transition-all shrink-0"
        >
          {state === "submitting" ? "Saving…" : "Save"}
        </button>
      </div>
      {errorMsg && <p className="text-xs text-red-400 mt-2">{errorMsg}</p>}
    </div>
  );
}


// Battery degradation chart driven by real battery data from the report.
// Plots the industry-standard expected degradation curve (from the engine's
// cycle anchors) and marks the user's actual current health point.
function BatteryDegradationChart({ battery }: { battery: { health?: number | null; cycleCount?: number | null } | null | undefined }) {
  // Expected degradation curve — matches cycleAnchors in engine.ts exactly
  const curvePoints = [
    { cycles: 0, expected: 100 },
    { cycles: 100, expected: 97 },
    { cycles: 200, expected: 92 },
    { cycles: 300, expected: 85 },
    { cycles: 500, expected: 75 },
    { cycles: 700, expected: 65 },
    { cycles: 1000, expected: 50 },
  ];

  const health = battery?.health;
  const cycles = battery?.cycleCount;

  // User's exact cycle position — always inserted so the dot is always visible
  const userPoint = cycles != null && health != null
    ? { cycles, expected: (() => {
        // Interpolate expected at user's exact cycle count from the curve
        for (let i = 1; i < curvePoints.length; i++) {
          const p0 = curvePoints[i - 1];
          const p1 = curvePoints[i];
          if (cycles <= p1.cycles) {
            const t = (cycles - p0.cycles) / (p1.cycles - p0.cycles);
            return p0.expected + t * (p1.expected - p0.expected);
          }
        }
        return curvePoints[curvePoints.length - 1].expected;
      })(), actual: health }
    : null;

  // Build chart data: merge curve points + user's exact position into a sorted series
  const baseData = curvePoints.map((p) => ({ cycles: p.cycles, expected: p.expected, actual: null as number | null }));
  const chartData = userPoint
    ? [...baseData, { cycles: userPoint.cycles, expected: userPoint.expected, actual: userPoint.actual }]
        .sort((a, b) => a.cycles - b.cycles)
    : baseData;

  // Determine how the user compares to expectations
  const gap =
    health != null && cycles != null
      ? (() => {
          // Interpolate expected value at user's cycle count
          for (let i = 1; i < curvePoints.length; i++) {
            const p0 = curvePoints[i - 1];
            const p1 = curvePoints[i];
            if (cycles <= p1.cycles) {
              const t = (cycles - p0.cycles) / (p1.cycles - p0.cycles);
              return (p0.expected + t * (p1.expected - p0.expected)) - health;
            }
          }
          return 0;
        })()
      : null;

  if (!battery || (health == null && cycles == null)) {
    return (
      <div className="surface-card rounded-2xl p-6 border border-border/60 mb-6 flex items-center justify-center h-48">
        <p className="text-sm text-muted-foreground/50">Battery data not available for this system</p>
      </div>
    );
  }

  return (
    <div className="surface-card rounded-2xl p-6 border border-border/60 mb-6">
      <div className="flex flex-wrap items-center justify-between gap-4 mb-5">
        <div>
          <h3 className="text-sm font-semibold text-foreground mb-1">Battery Degradation Curve</h3>
          <p className="text-xs text-muted-foreground">
            Your battery vs. expected health at {cycles ?? "?"} charge cycles
            {gap != null && gap > 5
              ? ` · ${gap.toFixed(0)}pts below expected — degrading faster than average`
              : gap != null && gap < -5
              ? ` · ${Math.abs(gap).toFixed(0)}pts above expected — degrading slower than average`
              : " · degrading at expected rate"}
          </p>
        </div>
        {health != null && (
          <div className={`px-3 py-1.5 rounded-lg text-xs font-semibold border ${
            health >= 80 ? "border-emerald-500/40 text-emerald-400 bg-emerald-500/10" :
            health >= 60 ? "border-yellow-500/40 text-yellow-400 bg-yellow-500/10" :
            "border-red-500/40 text-red-400 bg-red-500/10"
          }`}>
            {health.toFixed(1)}% actual health
          </div>
        )}
      </div>

      <div className="h-52 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={chartData} margin={{ top: 5, right: 10, left: -25, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
            <XAxis
              dataKey="cycles"
              stroke="#ffffff40"
              fontSize={10}
              tickMargin={8}
              tickFormatter={(v) => `${v}cy`}
            />
            <YAxis domain={[40, 100]} stroke="#ffffff40" fontSize={10} tickFormatter={(v) => `${v}%`} />
            <Tooltip
              contentStyle={{ backgroundColor: "#0f172a", borderColor: "#334155", borderRadius: "8px", fontSize: "11px" }}
              itemStyle={{ color: "#e2e8f0" }}
              formatter={(value: any, name: string) => [
                `${Number(value).toFixed(1)}%`,
                name === "expected" ? "Industry baseline" : "Your battery",
              ]}
              labelFormatter={(label) => `${label} cycles`}
            />

            {/* Replace zone: health < 60% */}
            <ReferenceArea y1={0} y2={60} fill="#ef4444" fillOpacity={0.05} />
            <ReferenceLine y={60} stroke="#ef4444" strokeDasharray="4 4" strokeOpacity={0.4}
              label={{ value: "Replace threshold", position: "insideTopRight", fill: "#ef4444", fontSize: 9, opacity: 0.7 }} />

            {/* Expected degradation curve */}
            <Line
              type="monotone"
              dataKey="expected"
              stroke="#ffffff35"
              strokeWidth={2}
              dot={false}
              name="expected"
              strokeDasharray="5 5"
              isAnimationActive={true}
              animationDuration={800}
            />

            {/* User's actual data point */}
            <Line
              type="monotone"
              dataKey="actual"
              stroke="#22d3ee"
              strokeWidth={0}
              dot={(props: any) => {
                if (props.value === null || props.value === undefined) return <></>;
                return (
                  <motion.circle
                    key="user-dot"
                    cx={props.cx}
                    cy={props.cy}
                    r={7}
                    fill="#22d3ee"
                    stroke="#0f172a"
                    strokeWidth={2}
                    initial={{ scale: 0, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    transition={{ delay: 0.9, type: "spring", stiffness: 250, damping: 18 }}
                  />
                );
              }}
              activeDot={{ r: 9, fill: "#22d3ee" }}
              name="actual"
              isAnimationActive={false}
            />
          </ComposedChart>
        </ResponsiveContainer>
      </div>

      <div className="mt-4 flex items-center gap-6 text-xs border-t border-border/30 pt-4">
        <div className="flex items-center gap-2 text-muted-foreground/60">
          <span className="w-6 h-px border-t-2 border-dashed border-white/30 inline-block" />
          Industry baseline
        </div>
        <div className="flex items-center gap-2 text-primary/80">
          <span className="w-3 h-3 rounded-full bg-cyan-400 inline-block" />
          Your battery
        </div>
        {gap != null && Math.abs(gap) > 3 && (
          <div className={`ml-auto font-medium ${gap > 0 ? "text-amber-400" : "text-emerald-400"}`}>
            {gap > 0 ? `▼ ${gap.toFixed(0)}pts below curve` : `▲ ${Math.abs(gap).toFixed(0)}pts above curve`}
          </div>
        )}
      </div>
    </div>
  );
}


function ExpandableFinding({ f, style, icon, troubleshootKey }: {
  f: any; style: any; icon: React.ReactNode; troubleshootKey: string;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`surface-card rounded-xl border-l-2 ${style.border} overflow-hidden`}>
      <button onClick={() => setOpen(o => !o)} className="w-full p-5 text-left flex items-start gap-3 hover:bg-muted/5 transition-colors">
        {icon}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-0.5 flex-wrap">
            <span className={`text-xs font-mono px-1.5 py-0.5 rounded border uppercase ${style.badge} shrink-0`}>{f.urgency}</span>
            <span className="text-xs font-mono text-muted-foreground/50">{f.component}</span>
          </div>
          <div className="text-sm font-semibold text-foreground">{f.title}</div>
          <p className="text-sm text-muted-foreground leading-relaxed mt-1">{f.body}</p>
        </div>
        <ChevronDown className={`w-4 h-4 text-muted-foreground/40 shrink-0 transition-transform duration-300 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div 
            initial={{ height: 0, opacity: 0, scaleY: 0, transformOrigin: "top" }}
            animate={{ height: "auto", opacity: 1, scaleY: 1 }}
            exit={{ height: 0, opacity: 0, scaleY: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 space-y-3 border-t border-border/30 pt-4">
          {f.oemContext && (
            <div className="rounded-lg bg-primary/5 border border-primary/15 px-4 py-3">
              <p className="text-xs font-mono text-primary/60 uppercase tracking-wide mb-1.5 flex items-center gap-1.5">
                <Shield className="w-3 h-3" /> Why OEM tools miss this
              </p>
              <p className="text-xs text-muted-foreground/80 leading-relaxed">{f.oemContext}</p>
              {f.caseStudyId && (
                <Link href={`/oem-failures#${f.caseStudyId}`} className="mt-2 inline-flex items-center gap-1 text-xs text-primary/70 hover:text-primary transition-colors">
                  See the real-world case study →
                </Link>
              )}
            </div>
          )}
          {troubleshootKey && (
            <Link href={`/troubleshoot?topic=${troubleshootKey}&title=${encodeURIComponent(f.title)}`} className="inline-flex items-center gap-2 text-xs font-semibold text-primary group relative">
              <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" /> Get step-by-step fix for this issue
              <div className="absolute -bottom-1 left-0 h-px bg-primary w-0 group-hover:w-full transition-all duration-200 ease-linear" />
            </Link>
          )}
        </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function ReproducibilityPanel({ result, combinedScoreVal }: { result: ReportResult; combinedScoreVal: number | null }) {
  const [open, setOpen] = useState(false);
  const weights: Record<string, number> = { Battery: 30, Thermals: 25, Storage: 25, Memory: 10, CPU: 10 };
  return (
    <div className="surface-card rounded-xl overflow-hidden border border-primary/20">
      <button onClick={() => setOpen(o => !o)} className="w-full flex items-center justify-between px-6 py-4 hover:bg-muted/5 transition-colors text-left">
        <div className="flex items-center gap-3">
          <Info className="w-4 h-4 text-primary/60" />
          <span className="text-sm font-semibold text-foreground">How this score was calculated</span>
          <span className="text-xs font-mono text-primary/50 border border-primary/20 bg-primary/5 px-2 py-0.5 rounded">v{result.algoVersion}</span>
        </div>
        <ChevronDown className={`w-4 h-4 text-muted-foreground/40 transition-transform duration-400 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div 
            initial={{ height: 0, opacity: 0, scaleY: 0, transformOrigin: "top" }}
            animate={{ height: "auto", opacity: 1, scaleY: 1 }}
            exit={{ height: 0, opacity: 0, scaleY: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="overflow-hidden"
          >
            <div className="border-t border-border/30 px-6 py-5 space-y-4">
              <p className="text-xs text-muted-foreground leading-relaxed">Each component is scored 0–100 using a deterministic formula, then weighted. The same inputs always produce the same output.</p>
          <div className="space-y-2">
            {result.components.map(c => {
              const w = weights[c.name] ?? 10;
              const contribution = Math.round(c.score * w / 100);
              return (
                <div key={c.name} className="rounded-lg bg-background/60 border border-border/40 px-4 py-3 font-mono text-xs">
                  <div className="flex justify-between mb-1">
                    <span className="text-foreground font-semibold">{c.name}</span>
                    <span className="text-muted-foreground">{c.score} × {w}% = <span className="text-primary font-bold">{contribution} pts</span></span>
                  </div>
                  <div className="text-muted-foreground/60">{c.detail}</div>
                </div>
              );
            })}
          </div>
          <div className="rounded-lg bg-primary/5 border border-primary/20 px-4 py-3 font-mono text-sm flex justify-between">
            <span className="text-muted-foreground">Hardware score</span>
            <span className="text-primary font-bold">{result.overall} / 100</span>
          </div>
          {combinedScoreVal !== null && (
            <div className="rounded-lg bg-primary/8 border border-primary/30 px-4 py-3 font-mono text-sm flex justify-between">
              <span className="text-muted-foreground">Combined (hardware 70% + habits 30%)</span>
              <span className="text-primary font-bold">{combinedScoreVal} / 100</span>
            </div>
          )}
          <Link href="/scoring" className="inline-flex items-center gap-1.5 text-xs text-primary/70 hover:text-primary transition-colors">
            Read the full scoring methodology <ArrowRight className="w-3 h-3" />
          </Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function Report() {
  const params = useParams<{ id: string }>();
  const [result, setResult] = useState<ReportResult | null>(null);
  const [habitScore, setHabitScore] = useState<number | null>(null);
  const [combinedScoreVal, setCombinedScoreVal] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loadedFrom, setLoadedFrom] = useState<"server" | "local" | null>(null);
  const [, navigate] = useLocation();
  const [showBanner, setShowBanner] = useState(true);

  useEffect(() => {
    if (result?.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0) {
      const timer = setTimeout(() => setShowBanner(false), 5000);
      return () => clearTimeout(timer);
    }
    return undefined;
  }, [result]);

  useEffect(() => {
    const id = params?.id;
    if (!id) { setError("No report ID provided."); return; }

    // Intercept claim token from URL if present (Direct Upload flow)
    const searchParams = new URLSearchParams(window.location.search);
    const urlClaimToken = searchParams.get("claim");
    if (urlClaimToken) {
      try {
        localStorage.setItem(`sentinel_claim_${id}`, urlClaimToken);
        // Clean URL to prevent accidental sharing of the claim token
        const cleanUrl = window.location.pathname;
        window.history.replaceState({}, document.title, cleanUrl);
      } catch (e) {
        console.error("Failed to save claim token", e);
      }
    }

    fetch(`/api/reports/${id}`)
      .then(async (res) => {
        if (res.ok) {
          const body = await res.json() as { result: ReportResult; habitScore: number | null; combinedScore: number | null };
          setResult(body.result);
          setHabitScore(body.habitScore);
          setCombinedScoreVal(body.combinedScore);
          setLoadedFrom("server");
          injectReportOG(body.result);
          return;
        }
        if (res.status === 404) {
          loadFromLocalStorage(id);
          // Opportunistic upload for legacy local IDs
          const stored = localStorage.getItem(`sentinel_report_${id}`);
          if (stored) {
            try {
              fetch("/api/reports", {
                method: "POST",
                headers: { "Content-Type": "application/json", "Idempotency-Key": `legacy-${id}` },
                body: JSON.stringify({ rawJson: JSON.parse(stored), legacy: true }),
              })
                .then(async (upRes) => {
                  if (upRes.ok) {
                    const { id: newId } = await upRes.json() as { id: string };
                    navigate(`/r/${newId}`);
                  }
                })
                .catch(() => {});
            } catch (e) { console.error("Legacy upload failed", e); }
          }
          return;
        }
        loadFromLocalStorage(id);
      })
      .catch(() => loadFromLocalStorage(id));
   
  }, [params?.id]);

  function loadFromLocalStorage(id: string) {
    const stored = localStorage.getItem(`sentinel_report_${id}`);
    if (!stored) {
      setError("Report not found. Reports are stored locally — this link only works on the device that generated it.");
      return;
    }
    try {
      const raw = JSON.parse(stored);
      const parsed = SentinelReportSchema.safeParse(raw);
      if (!parsed.success) { setError("Report data is corrupted or outdated."); return; }
      const r = generateReport(parsed.data);
      setResult(r);
      setLoadedFrom("local");
      injectReportOG(r);
    } catch {
      setError("Could not load report data.");
    }
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center px-6">
        <div className="max-w-md text-center">
          <Shield className="w-10 h-10 text-muted-foreground/30 mx-auto mb-4" />
          <h2 className="text-lg font-semibold mb-2">Report not found</h2>
          <p className="text-sm text-muted-foreground mb-6 leading-relaxed">{error}</p>
          <Link href="/health-test" className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-background bg-primary glow-cyan">
            Generate a new report <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="min-h-screen bg-background px-6 py-12">
        <div className="max-w-3xl mx-auto space-y-6 animate-pulse">
          {/* Header skeleton */}
          <div className="h-16 bg-card/60 rounded-2xl border border-border/40" />
          {/* Score card skeleton */}
          <div className="bg-card/60 rounded-2xl border border-border/40 p-7">
            <div className="flex gap-8 items-center">
              <div className="w-36 h-36 rounded-full bg-border/30 shrink-0" />
              <div className="flex-1 space-y-3">
                <div className="h-10 bg-border/30 rounded-lg w-40" />
                <div className="h-4 bg-border/20 rounded w-72" />
                <div className="h-4 bg-border/20 rounded w-52" />
                <div className="flex gap-2 mt-2">
                  <div className="h-6 w-20 bg-border/20 rounded-full" />
                  <div className="h-6 w-24 bg-border/20 rounded-full" />
                </div>
              </div>
            </div>
          </div>
          {/* Component cards skeleton */}
          <div className="bg-card/60 rounded-2xl border border-border/40 p-7 space-y-5">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="space-y-2">
                <div className="flex justify-between">
                  <div className="h-4 bg-border/30 rounded w-24" />
                  <div className="h-4 bg-border/30 rounded w-8" />
                </div>
                <div className="h-2 bg-border/20 rounded-full" />
                <div className="h-3 bg-border/10 rounded w-3/4" />
              </div>
            ))}
          </div>
          {/* Findings skeleton */}
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="h-20 bg-card/60 rounded-xl border border-border/40" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  const id = params?.id ?? "";
  const urgencyOrder = { critical: 0, warning: 1, info: 2 } as const;
  const publicFindings = result.findings.filter((f) => !f.pro).sort((a, b) => urgencyOrder[a.urgency] - urgencyOrder[b.urgency]);
  const proFindings    = result.findings.filter((f) => f.pro);
  const genDate = new Date(result.generatedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  return (
    <div className="min-h-screen bg-background text-foreground report-printable">
      <AnimatePresence>
        {result?.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0 && showBanner && (
          <motion.div 
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -20, opacity: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="w-full border-b border-red-500/40 bg-red-500/10 px-6 py-3"
          >
            <div className="max-w-3xl mx-auto flex items-center gap-3">
              <AlertTriangle className="w-4 h-4 text-red-400 shrink-0" />
              <div>
                <span className="text-xs font-bold text-red-400 uppercase tracking-wider">Data Collection Notes · </span>
                <span className="text-xs text-red-400/80">{result.dataQuality.structuredWarnings.map((w: any) => w.title).join(" · ")} — some telemetry was excluded from scoring.</span>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      {loadedFrom === "local" && (
        <div className="w-full bg-amber-500 text-amber-950 px-6 py-4 flex items-center justify-center gap-3 shadow-md z-50 relative">
          <AlertTriangle className="w-5 h-5 shrink-0" />
          <p className="text-sm font-bold">
            This report was scored offline and has not been verified by Sentinel servers. Scores may differ from the server-computed result.
          </p>
        </div>
      )}

      {/* Report header */}
      <div className="border-b border-border/60 bg-card/20 px-6 py-5">
        <AnimateIn>
          <div className="max-w-3xl mx-auto flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center">
                <Shield className="w-4 h-4 text-primary" />
              </div>
              <div>
                <div className="text-xs font-mono text-muted-foreground/60 uppercase tracking-wide">Sentinel Hardware Report</div>
                <div className="text-sm font-semibold">{result.system.model}</div>
              </div>
            </div>
            <div className="flex items-center gap-3">
              {loadedFrom === "server" && (
                <span className="text-xs font-mono text-green-400/60 border border-green-400/20 bg-green-400/5 px-2 py-0.5 rounded-full">
                  synced
                </span>
              )}
              <div className="text-xs font-mono text-muted-foreground/50">{genDate}</div>
            </div>
          </div>
        </AnimateIn>
      </div>

      <div className="px-6 py-12">
        <div className="max-w-3xl mx-auto space-y-8">

          {/* Overall score */}
          <AnimateIn>
            <div className="surface-card rounded-2xl overflow-hidden">
              {/* Grade header strip */}
              <div
                className="px-7 py-3 flex items-center justify-between"
                style={{
                  background:
                    (combinedScoreVal ?? result.overall) >= 80
                      ? "linear-gradient(90deg, #06b6d415, transparent)"
                      : (combinedScoreVal ?? result.overall) >= 60
                      ? "linear-gradient(90deg, #d9770615, transparent)"
                      : "linear-gradient(90deg, #ef444415, transparent)",
                  borderBottom: "1px solid rgba(255,255,255,0.04)",
                }}
              >
                <div className="flex items-center gap-2.5">
                  <CheckCircle2
                    className="w-4 h-4"
                    style={{
                      color:
                        (combinedScoreVal ?? result.overall) >= 80
                          ? "#22d3ee"
                          : (combinedScoreVal ?? result.overall) >= 60
                          ? "#f59e0b"
                          : "#f87171",
                    }}
                  />
                  <span className="text-xs font-mono text-muted-foreground/60 uppercase tracking-widest">
                    Sentinel Hardware Audit
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  {loadedFrom === "synced" && (
                    <span className="text-xs font-mono text-green-400/60 border border-green-400/20 bg-green-400/5 px-2 py-0.5 rounded-full">
                      verified
                    </span>
                  )}
                  {loadedFrom === "local" && (
                    <span className="text-xs font-mono text-amber-500 border border-amber-500/30 bg-amber-500/10 px-2 py-0.5 rounded-full flex items-center gap-1">
                      <AlertTriangle className="w-3 h-3" /> unverified
                    </span>
                  )}
                  <span className="text-xs font-mono text-muted-foreground/40">v{result.algoVersion}</span>
                </div>
              </div>

              {/* Main score layout — grid so it never wraps awkwardly */}
              <div className="p-7 grid grid-cols-[auto_1fr] gap-8 items-center">
                {/* Left: Score ring (no duplicate text overlay here — ring renders its own number) */}
                <ScoreRing score={combinedScoreVal ?? result.overall} size={148} />

                {/* Right: Grade + summary */}
                <div className="min-w-0">
                  <div className="flex items-baseline gap-3 mb-1 flex-wrap">
                    <span
                      className="text-5xl font-black tracking-tight leading-none"
                      style={{
                        color:
                          (combinedScoreVal ?? result.overall) >= 80
                            ? "#22d3ee"
                            : (combinedScoreVal ?? result.overall) >= 60
                            ? "#f59e0b"
                            : "#f87171",
                      }}
                    >
                      {result.grade}
                    </span>
                    <span className="text-xl font-semibold text-foreground/80">{result.gradeLabel}</span>
                  </div>

                  {/* Hardware + habit breakdown row */}
                  {combinedScoreVal !== null ? (
                    <div className="flex items-center gap-2 mb-3 flex-wrap">
                      <span className="text-xs font-mono text-muted-foreground/50 bg-muted/20 border border-border/30 px-2 py-0.5 rounded">
                        Hardware {result.overall}
                      </span>
                      <span className="text-xs text-muted-foreground/30">+</span>
                      <span className="text-xs font-mono text-accent/80 bg-accent/8 border border-accent/20 px-2 py-0.5 rounded">
                        Habits {habitScore}
                      </span>
                      <span className="text-xs text-muted-foreground/30">→</span>
                      <span className="text-xs font-mono text-primary font-semibold bg-primary/8 border border-primary/20 px-2 py-0.5 rounded">
                        Combined {combinedScoreVal}
                      </span>
                    </div>
                  ) : (
                    <div className="h-3 mb-3" />
                  )}

                  <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                    {(() => {
                      const score = combinedScoreVal ?? result.overall;
                      const criticalComponents = result.components.filter(c => c.status === "critical");
                      const attentionComponents = result.components.filter(c => c.status === "attention");
                      const criticalFindings = publicFindings.filter(f => f.urgency === "critical");

                      if (score >= 85 && criticalComponents.length === 0) {
                        const topComponent = result.components.reduce((a, b) => a.score > b.score ? a : b);
                        return `All components are operating within healthy parameters. ${topComponent.name} is performing best at ${topComponent.score}/100.`;
                      } else if (criticalComponents.length > 0) {
                        const names = criticalComponents.map(c => `${c.name} (${c.score}/100)`).join(" and ");
                        return `${names} ${criticalComponents.length === 1 ? "is" : "are"} in critical condition and ${criticalComponents.length === 1 ? "requires" : "require"} immediate attention. ${criticalFindings.length > 0 ? `${criticalFindings.length} critical finding${criticalFindings.length > 1 ? "s" : ""} flagged — review below.` : ""}`;
                      } else if (attentionComponents.length > 0) {
                        const names = attentionComponents.map(c => `${c.name} (${c.score}/100)`).join(" and ");
                        return `${names} ${attentionComponents.length === 1 ? "needs" : "need"} attention. Review the findings below for specific recommendations.`;
                      } else {
                        const lowestComponent = result.components.reduce((a, b) => a.score < b.score ? a : b);
                        return `Hardware is generally healthy. ${lowestComponent.name} has the lowest score at ${lowestComponent.score}/100 — keep an eye on it.`;
                      }
                    })()}
                  </p>

                  {/* Finding summary pills */}
                  <div className="flex flex-wrap gap-2 text-xs">
                    {publicFindings.filter((f) => f.urgency === "critical").length > 0 && (
                      <span className="text-red-400 bg-red-400/8 border border-red-400/25 px-2.5 py-1 rounded-full font-mono font-medium">
                        ⚠ {publicFindings.filter((f) => f.urgency === "critical").length} critical
                      </span>
                    )}
                    {publicFindings.filter((f) => f.urgency === "warning").length > 0 && (
                      <span className="text-amber-400 bg-amber-400/8 border border-amber-400/25 px-2.5 py-1 rounded-full font-mono font-medium">
                        ▲ {publicFindings.filter((f) => f.urgency === "warning").length} warnings
                      </span>
                    )}
                    <span className="text-cyan-400/70 bg-cyan-400/5 border border-cyan-400/20 px-2.5 py-1 rounded-full font-mono">
                      ✓ {publicFindings.filter((f) => f.urgency === "info").length} healthy
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </AnimateIn>

          {/* ── Data Quality Transparency Banners ───────────────────────── */}
          {result.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0 && (
            <AnimateIn delay={0.04}>
              <div className="space-y-3">
                {result.dataQuality.structuredWarnings.map((w, i) => {
                  const isHigh = w.severity === "high";
                  return (
                    <div
                      key={i}
                      className={`rounded-xl border overflow-hidden ${
                        isHigh
                          ? "border-amber-500/40 bg-amber-500/8"
                          : "border-amber-500/20 bg-amber-500/5"
                      }`}
                    >
                      {/* Banner header */}
                      <div className={`px-5 py-3 flex items-center gap-3 ${
                        isHigh ? "bg-amber-500/15 border-b border-amber-500/20" : "border-b border-amber-500/10"
                      }`}>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                          isHigh ? "bg-amber-500/20" : "bg-amber-500/10"
                        }`}>
                          <AlertTriangle className={`w-4 h-4 ${isHigh ? "text-amber-400" : "text-amber-500/70"}`} />
                        </div>
                        <div className="flex-1">
                          <h3 className={`text-sm font-bold ${isHigh ? "text-amber-400" : "text-amber-500/80"}`}>
                            {w.title}
                          </h3>
                          {w.excludedFromScoring && (
                            <span className="text-xs font-mono text-amber-500/50 mt-0.5 block">
                              EXCLUDED FROM OVERALL SCORE
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Banner body */}
                      <div className="px-5 py-4 space-y-3">
                        <p className="text-sm text-muted-foreground leading-relaxed">{w.detail}</p>
                        {w.oemComparison && (
                          <div className="rounded-lg bg-background/60 border border-border/40 px-4 py-3">
                            <p className="text-xs font-mono text-muted-foreground/50 uppercase tracking-wide mb-1.5">
                              vs. OEM tools
                            </p>
                            <p className="text-xs text-muted-foreground/80 leading-relaxed">{w.oemComparison}</p>
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Legacy fallback: plain-text data quality warnings (only if no structured ones) */}
          {(!result.dataQuality?.structuredWarnings || result.dataQuality.structuredWarnings.length === 0) &&
            result.dataQuality?.warnings && result.dataQuality.warnings.length > 0 && (
            <AnimateIn delay={0.04}>
              <div className="surface-card rounded-xl p-5 border border-amber-500/20 bg-amber-500/5">
                <div className="flex items-center gap-3 mb-3">
                  <Info className="w-4 h-4 text-amber-500" />
                  <h2 className="text-sm font-bold text-amber-500 uppercase tracking-wider">Data Collection Notes</h2>
                </div>
                <ul className="space-y-2">
                  {result.dataQuality.warnings.map((w: string, i: number) => (
                    <li key={i} className="text-sm text-amber-500/80 list-disc list-inside">{w}</li>
                  ))}
                </ul>
              </div>
            </AnimateIn>
          )}

          {/* System Info Tile */}
          <AnimateIn delay={0.05}>
            <div className="surface-card rounded-2xl p-6 border border-border/30">
              <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest mb-4">System Information</h2>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-6 gap-y-3 text-xs font-mono">
                <div>
                  <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">Model</div>
                  <div className="text-foreground font-medium truncate" title={result.system.model}>{result.system.model || "Unknown"}</div>
                </div>
                <div>
                  <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">OS</div>
                  <div className="text-foreground truncate" title={result.system.os}>{result.system.os || "Unknown"}</div>
                </div>
                <div>
                  <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">Hostname</div>
                  <div className="text-foreground truncate">{result.system.hostname || "—"}</div>
                </div>
                {result.rawReport?.system?.biosVersion && (
                  <div>
                    <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">BIOS / UEFI</div>
                    <div className="text-foreground truncate" title={result.rawReport.system.biosVersion}>{result.rawReport.system.biosVersion}</div>
                  </div>
                )}
                {result.rawReport?.system?.bootTime && (
                  <div>
                    <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">Last Boot</div>
                    <div className="text-foreground">{new Date(result.rawReport.system.bootTime).toLocaleString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</div>
                  </div>
                )}
                {result.rawReport?.system?.uptimeHours != null && (
                  <div>
                    <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">Uptime</div>
                    <div className="text-foreground">{result.rawReport.system.uptimeHours < 24
                      ? `${result.rawReport.system.uptimeHours.toFixed(0)}h`
                      : `${(result.rawReport.system.uptimeHours / 24).toFixed(0)}d ${(result.rawReport.system.uptimeHours % 24).toFixed(0)}h`}</div>
                  </div>
                )}
                {result.rawReport?.cpu?.name && (
                  <div className="col-span-2 sm:col-span-3">
                    <div className="text-muted-foreground/40 mb-0.5 uppercase tracking-wide text-[10px]">Processor</div>
                    <div className="text-foreground truncate" title={result.rawReport.cpu.name}>{result.rawReport.cpu.name}{result.rawReport.cpu.cores ? ` · ${result.rawReport.cpu.cores} cores` : ""}</div>
                  </div>
                )}
              </div>
            </div>
          </AnimateIn>

          {/* Component breakdown — staggered animated */}
          <div className="surface-card rounded-2xl p-7">
            <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest mb-6">Component breakdown</h2>
            <div className="space-y-6">
              {result.components.map((c, idx) => {
                const s = STATUS_STYLES[c.status];
                const scoreColor = c.score >= 80 ? "#22d3ee" : c.score >= 60 ? "#f59e0b" : "#f87171";
                const raw = result.rawReport;

                // ── Data-driven narrative per component ──────────────────
                let narrative = c.detail; // fallback = engine detail string

                if (c.name === "Battery" && raw.battery) {
                  const b = raw.battery;
                  const health = b.health;
                  const cycles = b.cycleCount;
                  const drainMw = b.dischargeRateMw != null && b.dischargeRateMw < 0 ? Math.abs(b.dischargeRateMw) : null;
                  const drainW = drainMw ? (drainMw / 1000).toFixed(1) : null;
                  const fullWh = b.fullChargeCapacity ? (b.fullChargeCapacity / 1000).toFixed(1) : null;
                  const designWh = b.designCapacity ? (b.designCapacity / 1000).toFixed(1) : null;
                  // Estimate runtime: fullChargeCapacity (mWh) / |dischargeRateMw| = hours
                  const runtimeHrs = (drainMw && b.fullChargeCapacity)
                    ? (b.fullChargeCapacity / drainMw).toFixed(1)
                    : null;

                  if (health != null && cycles != null) {
                    const lostPct = (100 - health).toFixed(0);
                    const whStr = fullWh && designWh ? ` (${fullWh} Wh of ${designWh} Wh rated)` : "";
                    const runtimeStr = runtimeHrs ? ` Est. ${runtimeHrs}h runtime at current draw (${drainW}W).` : drainW ? ` Current draw: ${drainW}W.` : "";
                    if (c.score >= 80) {
                      narrative = `Battery retains ${health.toFixed(1)}% capacity${whStr} at ${cycles} cycles.${runtimeStr} Degradation within normal range — no action needed.`;
                    } else if (c.score >= 60) {
                      narrative = `Battery has lost ${lostPct}% of original capacity${whStr} over ${cycles} cycles.${runtimeStr} Runtime is measurably shorter. Plan replacement within 6–12 months.`;
                    } else {
                      narrative = `Battery severely degraded: ${health.toFixed(1)}% remaining${whStr} at ${cycles} cycles.${runtimeStr} Unexpected shutdowns at 10–20% reported charge are likely. Replace soon.`;
                    }
                  } else if (health != null) {
                    const runtimeStr = runtimeHrs ? ` Est. ${runtimeHrs}h runtime at current draw.` : "";
                    narrative = `Battery retains ${health.toFixed(1)}% of original capacity.${runtimeStr} ${c.score >= 80 ? "No action needed." : "Degradation is measurable — monitor closely."}`;
                  }
                }

                else if (c.name === "Thermals" && raw.thermals) {
                  const t = raw.thermals;
                  const maxTemp = t.maxTempC;
                  const throttle = t.throttleEvents30min ?? 0;
                  const source = t.thermalSource ?? "";
                  const srcLabel: Record<string, string> = {
                    performance_counter: "Win32 Performance Counter",
                    acpi_wmi: "ACPI/WMI",
                    ohm: "OpenHardwareMonitor",
                    lhm: "LibreHardwareMonitor",
                  };
                  const srcStr = srcLabel[source] ?? source;
                  if (maxTemp != null) {
                    const THROTTLE_TEMP = 100;
                    const headroom = THROTTLE_TEMP - maxTemp;
                    const headroomStr = headroom > 0
                      ? ` ${headroom.toFixed(0)}°C of headroom before throttle limit.`
                      : " Throttle threshold exceeded.";
                    const throttleStr = throttle > 0
                      ? ` ${throttle} thermal throttle event${throttle > 1 ? "s" : ""} in last 30min — CPU clock was reduced.`
                      : " No throttle events.";
                    if (c.score >= 80) {
                      narrative = `Peak: ${maxTemp.toFixed(1)}°C — within safe limits.${headroomStr}${throttleStr} Source: ${srcStr || "System"}.`;
                    } else if (c.score >= 60) {
                      narrative = `Peak: ${maxTemp.toFixed(1)}°C — above ideal sustained range.${headroomStr}${throttleStr} Check vent clearance. Source: ${srcStr || "System"}.`;
                    } else {
                      narrative = `Peak: ${maxTemp.toFixed(1)}°C — critical zone.${headroomStr}${throttleStr} Thermal paste replacement and deep vent cleaning recommended. Source: ${srcStr || "System"}.`;
                    }
                  }
                }

                else if (c.name === "Storage" && raw.storage?.[0]) {
                  const st = raw.storage[0];
                  const model = st.model ?? "Drive";
                  const wear = st.wearLevelPct ?? st.healthPct;
                  const free = st.freeSpacePct;
                  const realloc = st.reallocatedSectors ?? 0;
                  const poh = st.powerOnHours ?? 0;
                  const freeStr = free != null ? ` ${free.toFixed(1)}% free space remaining.` : " Free space data unavailable.";
                  const pohStr = poh > 0 ? ` Power-on hours: ${poh.toLocaleString()}h.` : "";
                  const reallocStr = realloc > 0 ? ` ⚠ ${realloc} reallocated sector${realloc > 1 ? "s" : ""} detected — physical media damage present.` : "";
                  if (wear != null) {
                    const consumed = (100 - wear).toFixed(0);
                    if (c.score >= 80) {
                      narrative = `${model}: ${wear}% endurance remaining (${consumed}% of rated write life consumed).${freeStr}${pohStr}${reallocStr} Drive health is in good condition.`;
                    } else if (c.score >= 60) {
                      narrative = `${model}: ${wear}% endurance remaining.${freeStr}${pohStr}${reallocStr} Drive is in the monitoring zone — maintain regular backups and consider upgrade planning.`;
                    } else {
                      narrative = `${model}: only ${wear}% endurance remaining.${freeStr}${pohStr}${reallocStr} Write endurance is critically low. Imminent performance degradation or failure is possible — back up all data now.`;
                    }
                  } else {
                    if (c.score >= 80) {
                      narrative = `${model}:${freeStr}${pohStr}${reallocStr} Health data was not directly readable — score reflects available indicators.`;
                    } else {
                      narrative = `${model}:${freeStr}${pohStr}${reallocStr} Health data was not directly readable. Low free space or high runtime hours are contributing to the lower score.`;
                    }
                  }
                }

                else if (c.name === "Memory" && raw.memory) {
                  const m = raw.memory;
                  const usedPct = m.usedPct.toFixed(1);
                  const totalGB = m.totalGB;
                  const pf = m.pageFaultsPerSec;
                  const freeGB = ((1 - m.usedPct / 100) * totalGB).toFixed(1);
                  const PF_BASELINE = 500;
                  const pfStr = pf != null && pf > PF_BASELINE
                    ? ` Page fault rate: ${pf.toLocaleString()}/s (×${(pf / PF_BASELINE).toFixed(1)} above healthy idle baseline of ${PF_BASELINE}/s) — active SSD pagefile use.`
                    : pf != null && pf > 10
                    ? ` Page fault rate: ${pf.toLocaleString()}/s.`
                    : "";
                  if (c.score >= 80) {
                    narrative = `${totalGB} GB RAM · ${usedPct}% in use (${freeGB} GB free). Memory headroom is adequate for current workload.${pfStr}`;
                  } else if (c.score >= 60) {
                    narrative = `${totalGB} GB RAM · ${usedPct}% in use (${freeGB} GB free). Memory is moderately pressured — additional apps or browser tabs will trigger pagefile activity.${pfStr}`;
                  } else {
                    narrative = `${totalGB} GB RAM · ${usedPct}% in use (only ${freeGB} GB free). System is under heavy memory pressure. Windows is actively using the SSD as a memory extension, causing latency spikes and accelerating drive wear.${pfStr}`;
                  }
                }

                else if (c.name === "CPU" && raw.cpu) {
                  const cpu = raw.cpu;
                  const name = cpu.name ?? "CPU";
                  const load = cpu.avgLoadPct;
                  const throttle = cpu.throttleEvents30min ?? 0;
                  const cores = cpu.cores;
                  const coreStr = cores ? ` (${cores}-core)` : "";
                  const loadStr = load != null ? ` Average load: ${load.toFixed(1)}%.` : "";
                  const throttleStr = throttle > 0
                    ? ` ${throttle} thermal throttle event${throttle > 1 ? "s" : ""} in the last 30 minutes — processor is reducing clock speed due to heat.`
                    : " No throttle events.";
                  if (c.score >= 80) {
                    narrative = `${name}${coreStr}.${loadStr}${throttleStr} CPU is operating efficiently.`;
                  } else if (c.score >= 60) {
                    narrative = `${name}${coreStr}.${loadStr}${throttleStr} CPU load or throttling is moderately elevated — cooling system maintenance may improve performance.`;
                  } else {
                    narrative = `${name}${coreStr}.${loadStr}${throttleStr} CPU is being significantly thermally limited. Effective performance is lower than hardware spec due to sustained throttling.`;
                  }
                }

                return (
                  <motion.div key={c.name} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 + idx * 0.1, duration: 0.4, ease: [0.25, 0.1, 0.25, 1] }}>
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-semibold text-foreground">{c.name}</span>
                        <span className={`text-xs px-1.5 py-0.5 rounded border ${s.badge} font-mono`}>{c.status}</span>
                      </div>
                      <span className="text-lg font-bold font-mono tabular-nums" style={{ color: scoreColor }}>{c.score}</span>
                    </div>
                    <div className="h-2 bg-border/20 rounded-full overflow-hidden mb-3">
                      <motion.div className={`h-full rounded-full ${s.bar}`} initial={{ width: 0 }} animate={{ width: `${c.score}%` }} transition={{ delay: 0.2 + idx * 0.15, duration: 0.8, ease: "easeOut" }} />
                    </div>
                    <p className="text-xs text-muted-foreground leading-relaxed">{narrative}</p>
                  </motion.div>
                );
              })}
            </div>
          </div>


          {/* Advanced System Diagnostics */}
          <AnimateIn delay={0.05}>
            <AdvancedDiagnostics report={result.rawReport} />
          </AnimateIn>

          {/* ── Health Forecast Timeline ────────────────────────────────────── */}
          {result.predictions && result.predictions.length > 0 && (
            <AnimateIn delay={0.06}>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Health Forecast Timeline</h2>
                  <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-primary/10 border border-primary/30 text-primary flex items-center gap-1">
                    <Clock className="w-3 h-3" /> FORECAST
                  </span>
                </div>
                <p className="text-xs text-muted-foreground/50 leading-relaxed -mt-1 mb-1">
                  How long before each component becomes a problem — based on current readings and degradation curves.
                </p>
                <BatteryDegradationChart battery={result.rawReport?.battery ?? null} />
                {result.predictions.map((pred, i) => {
                  const severityStyles = {
                    stable: {
                      border: "border-l-green-400",
                      icon: <CheckCircle2 className="w-4 h-4 text-green-400" />,
                      badge: "text-green-400 bg-green-400/8 border-green-400/20",
                      badgeLabel: "Stable",
                      glow: "bg-green-400",
                    },
                    declining: {
                      border: "border-l-amber-400",
                      icon: <TrendingDown className="w-4 h-4 text-amber-400" />,
                      badge: "text-amber-400 bg-amber-400/8 border-amber-400/20",
                      badgeLabel: "Declining",
                      glow: "bg-amber-400",
                    },
                    urgent: {
                      border: "border-l-red-400",
                      icon: <AlertTriangle className="w-4 h-4 text-red-400" />,
                      badge: "text-red-400 bg-red-400/8 border-red-400/20",
                      badgeLabel: "Urgent",
                      glow: "bg-red-400",
                    },
                  };
                  const s = severityStyles[pred.severity];
                  return (
                    <div key={i} className={`surface-card rounded-xl p-5 border-l-2 ${s.border}`}>
                      <div className="flex items-start justify-between gap-4 mb-3">
                        <div className="flex items-center gap-3">
                          {s.icon}
                          <div>
                            <div className="text-sm font-semibold text-foreground">{pred.component}</div>
                            <div className="text-xs font-mono text-muted-foreground/50 mt-0.5">{pred.currentValue}</div>
                          </div>
                        </div>
                        <span className={`text-xs font-mono px-2 py-0.5 rounded-full border shrink-0 ${s.badge}`}>
                          {s.badgeLabel}
                        </span>
                      </div>
                      {/* Timeline bar */}
                      <div className="rounded-lg bg-muted/10 border border-border/30 px-4 py-3 mb-3">
                        <div className="flex items-center gap-2 mb-1">
                          <Clock className="w-3 h-3 text-muted-foreground/40" />
                          <span className="text-xs font-mono text-muted-foreground/50 uppercase tracking-wide">Projected Timeline</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className={`w-2 h-2 rounded-full ${s.glow} animate-glow-pulse shrink-0`} />
                          <span className="text-sm font-medium text-foreground">{pred.projectedTimeline}</span>
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">{pred.insight}</p>
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Public findings — expandable */}
          {publicFindings.length > 0 && (
            <AnimateIn delay={0.07}>
              <div className="space-y-3">
                <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Findings</h2>
                {publicFindings.map((f, i) => {
                  const style = URGENCY_STYLES[f.urgency];
                  const dot = f.urgency === "critical" ? "bg-red-400" : f.urgency === "warning" ? "bg-amber-400" : "bg-cyan-400";
                  const tk: Record<string, string> = { Battery: "battery", Thermals: "thermal", Storage: "storage", Memory: "memory", CPU: "cpu" };
                  return (
                    <ExpandableFinding key={i} f={f} style={style} icon={<span className={`w-2 h-2 rounded-full ${dot} shrink-0 mt-2`} />} troubleshootKey={tk[f.component] ?? ""} />
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Pro findings (blurred) */}
          {proFindings.length > 0 && (
            <AnimateIn delay={0.08}>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Diagnostic findings</h2>
                  <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-accent/10 border border-accent/30 text-accent">PRO</span>
                </div>
                {proFindings.map((f, i) => (
                  <div key={i} className="surface-card rounded-xl p-5 border border-accent/20 relative overflow-hidden">
                    <div className="absolute inset-0 backdrop-blur-sm bg-background/60 z-10 flex items-center justify-center rounded-xl">
                      <div className="text-center px-6">
                        <Lock className="w-5 h-5 text-accent mx-auto mb-2" />
                        <div className="text-sm font-semibold text-foreground mb-1">Pro finding</div>
                        <div className="text-xs text-muted-foreground mb-3">Pro diagnostic findings unlock with early access.</div>
                        <Link href="/waitlist" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold text-background bg-accent hover:bg-accent/90 transition-all">
                          Get early access <ArrowRight className="w-3 h-3" />
                        </Link>
                      </div>
                    </div>
                    <div className="opacity-20 select-none pointer-events-none" aria-hidden>
                      <div className="text-xs font-mono text-muted-foreground/50 mb-1">{f.component}</div>
                      <div className="text-sm font-semibold mb-2">{f.title}</div>
                      <p className="text-sm text-muted-foreground">{f.body}</p>
                    </div>
                  </div>
                ))}
              </div>
            </AnimateIn>
          )}

          {/* Score Reproducibility Panel */}
          <AnimateIn delay={0.075}>
            <ReproducibilityPanel result={result} combinedScoreVal={combinedScoreVal} />
          </AnimateIn>

          {/* Claim panel (only shown when user owns the report) */}
          <AnimateIn delay={0.06}>
            <ClaimPanel id={id} />
          </AnimateIn>

          {/* Share row */}
          <AnimateIn delay={0.07}>
            <SharePanel id={id} isLocal={loadedFrom === "local"} />
          </AnimateIn>

          {/* Footer */}
          <AnimateIn delay={0.08}>
            <div className="surface-card rounded-xl p-5 space-y-3">
              <div className="flex items-center justify-between flex-wrap gap-4">
                <div className="text-xs text-muted-foreground/60 leading-relaxed max-w-sm">
                  {loadedFrom === "server"
                    ? "This report is stored on Sentinel's servers and accessible from any device via the link above."
                    : "This report was generated from your device's hardware telemetry."}
                </div>
                <Link
                  href="/health-test"
                  className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-xs font-semibold border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all"
                >
                  Run another scan <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
              <div className="border-t border-border/30 pt-3 flex items-center justify-between flex-wrap gap-2">
                <span className="text-xs font-mono text-muted-foreground/40">
                  Algorithm v{result.algoVersion} · {genDate}
                </span>
                <Link
                  href="/changelog"
                  className="text-xs text-primary/60 hover:text-primary transition-colors flex items-center gap-1"
                >
                  Scoring methodology & changelog <ArrowRight className="w-3 h-3" />
                </Link>
              </div>
            </div>
          </AnimateIn>

        </div>
      </div>
    </div>
  );
}
