import React, { useEffect, useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ResponsiveContainer, ComposedChart, Line, Area, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ReferenceArea } from "recharts";

import { Link, useParams, useLocation } from "wouter";
import {
  ArrowRight, Shield, AlertTriangle, Info, Lock,
  Share2, Check, Copy, Mail, ChevronDown, TrendingDown, Clock, CheckCircle2, Printer,
} from "lucide-react";
import { generateReport, type ReportResult, type Prediction } from "@/lib/report/engine";
import { SentinelReportSchema } from "@/lib/report/schema";
import AnimateIn from "@/components/AnimateIn";

// ── OG meta injection ────────────────────────────────────────────────────────

/**
 * Dynamically injects open graph (OG) metadata properties into the document head.
 * 
 * @param property The meta property name.
 * @param content The value content of the property.
 */
function setMeta(property: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[property="${property}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("property", property);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

/**
 * Dynamically updates or creates a standard name-based meta tag in the head.
 * 
 * @param name The meta tag name attribute.
 * @param content The content value to inject.
 */
function setMetaName(name: string, content: string) {
  let el = document.querySelector<HTMLMetaElement>(`meta[name="${name}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute("name", name);
    document.head.appendChild(el);
  }
  el.setAttribute("content", content);
}

function injectReportOG(result: ReportResult) {
  const title = `${result.system.model} — ${result.grade} (${result.overall}/100) · Sentinel`;
  const desc = `Hardware health report: ${result.components.map((c) => `${c.name} ${c.score}/100`).join(" · ")}. Generated by Sentinel.`;
  document.title = title;
  setMeta("og:title", title);
  setMeta("og:description", desc);
  setMeta("og:type", "article");
  setMetaName("twitter:title", title);
  setMetaName("twitter:description", desc);
}

// ── Score ring ───────────────────────────────────────────────────────────────

const STATUS_STYLES = {
  healthy:   { bar: "bg-green-500",  badge: "text-green-400 border-green-400/20 bg-green-400/5"  },
  watch:     { bar: "bg-cyan-400",   badge: "text-cyan-400 border-cyan-400/20 bg-cyan-400/5"     },
  attention: { bar: "bg-amber-400",  badge: "text-amber-400 border-amber-400/20 bg-amber-400/5"  },
  critical:  { bar: "bg-red-400",    badge: "text-red-400 border-red-400/20 bg-red-400/5"        },
};

const URGENCY_STYLES = {
  critical: { border: "border-l-red-400",     badge: "text-red-400 bg-red-400/8 border-red-400/20"     },
  warning:  { border: "border-l-amber-400",   badge: "text-amber-400 bg-amber-400/8 border-amber-400/20" },
  info:     { border: "border-l-cyan-400/40", badge: "text-cyan-400 bg-cyan-400/8 border-cyan-400/20"   },
};

/**
 * Renders an interactive circular health score indicator ring with standard Apple-style
 * easing transitions.
 * 
 * @param score Overall computed hardware score.
 */
function ScoreRing({ score }: { score: number }) {
  const r = 54;
  const circ = 2 * Math.PI * r;
  const color = score >= 80 ? "#22d3ee" : score >= 60 ? "#f59e0b" : "#f87171";
  
  const [displayed, setDisplayed] = React.useState(0);

  React.useEffect(() => {
    import("framer-motion").then(({ animate }) => {
      animate(0, score, {
        duration: 0.8,
        ease: [0.25, 0.1, 0.25, 1],
        onUpdate: (val) => setDisplayed(Math.round(val))
      });
    });
  }, [score]);

  const dash = (displayed / 100) * circ;

  return (
    <div className="relative" style={{ width: 140, height: 140 }}>
      <svg width="140" height="140" viewBox="0 0 140 140" className="rotate-[-90deg] absolute inset-0">
        <circle cx="70" cy="70" r={r} fill="none" stroke="currentColor" strokeWidth="10" className="text-border/20" />
        <circle cx="70" cy="70" r={r} fill="none" stroke={color} strokeWidth="10"
          strokeDasharray={`${dash} ${circ}`} strokeLinecap="round"
          style={{ filter: `drop-shadow(0 0 8px ${color})` }} />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <div className="text-4xl font-bold tabular-nums" style={{ color }}>{displayed}</div>
        <div className="text-xs text-muted-foreground">/100</div>
      </div>
    </div>
  );
}

// ── Share + PDF panel ─────────────────────────────────────────────────────────

function SharePanel({ id, isLocal }: { id: string; isLocal?: boolean }) {
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copiedDirect, setCopiedDirect] = useState(false);

  const directUrl = `${window.location.origin}/r/${id}`;

  const generateShareLink = async () => {
    const claimToken = localStorage.getItem(`sentinel_claim_${id}`) ?? "";
    if (!claimToken) return;

    setGenerating(true);
    try {
      const res = await fetch(`/api/reports/${id}/share`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ claimToken }),
      });
      if (res.ok) {
        const { shareToken } = await res.json() as { shareToken: string };
        setShareUrl(`${window.location.origin}/s/${shareToken}`);
      }
    } catch {
      // silently fail — the direct link is still available
    } finally {
      setGenerating(false);
    }
  };

  const copyShareUrl = () => {
    const url = shareUrl ?? directUrl;
    navigator.clipboard.writeText(url).then(() => {
      if (shareUrl) {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } else {
        setCopiedDirect(true);
        setTimeout(() => setCopiedDirect(false), 2000);
      }
    });
  };

  const hasClaimToken = typeof window !== "undefined" && !!localStorage.getItem(`sentinel_claim_${id}`);

  return (
    <div className="surface-card rounded-xl p-5 space-y-4 print:hidden">
      <div className="flex items-center gap-2 mb-1">
        <Share2 className="w-4 h-4 text-primary/60" />
        <span className="text-sm font-medium text-foreground">Share this report</span>
      </div>

      {/* Public share link (stripped of PII) */}
      {hasClaimToken && !isLocal && (
        <div className="space-y-2">
          {!shareUrl ? (
            <button
              onClick={generateShareLink}
              disabled={generating}
              className="w-full text-left px-4 py-3 rounded-lg border border-primary/20 bg-primary/5 hover:bg-primary/8 transition-all group"
            >
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-sm font-medium text-foreground">
                    {generating ? "Generating…" : "Generate read-only link"}
                  </div>
                  <div className="text-xs text-muted-foreground/60 mt-0.5">
                    Creates a public link with just the score, components, and findings — no email or personal info.
                    Send it to a repair shop, a friend, or post it in a forum.
                  </div>
                </div>
                <ArrowRight className="w-4 h-4 text-primary/40 group-hover:text-primary transition-colors shrink-0 ml-3" />
              </div>
            </button>
          ) : (
            <div className="rounded-lg border border-green-400/20 bg-green-400/5 px-4 py-3">
              <div className="flex items-center gap-2 mb-1.5">
                <Check className="w-3.5 h-3.5 text-green-400" />
                <span className="text-xs font-medium text-green-400">Public link ready</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs text-muted-foreground/60 truncate flex-1">{shareUrl}</span>
                <button
                  onClick={copyShareUrl}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all shrink-0"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copied ? "Copied!" : "Copy"}
                </button>
              </div>
              <p className="text-[10px] text-muted-foreground/40 mt-2">This link shows only: score, components, findings, algorithm version. No email, no raw data.</p>
            </div>
          )}
        </div>
      )}

      {/* Direct link (fallback) */}
      <div className={`flex items-center justify-between flex-wrap gap-3 ${isLocal ? "opacity-40 blur-[2px] select-none pointer-events-none" : ""}`}>
        <span className="font-mono text-xs text-muted-foreground/60 truncate max-w-[220px]">{directUrl}</span>
        <button
          onClick={() => {
            navigator.clipboard.writeText(directUrl).then(() => {
              setCopiedDirect(true);
              setTimeout(() => setCopiedDirect(false), 2000);
            });
          }}
          disabled={isLocal}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all"
        >
          {copiedDirect ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
          {copiedDirect ? "Copied!" : "Copy direct link"}
        </button>
      </div>

      {/* Print / PDF */}
      <div className="border-t border-border/30 pt-3">
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all w-full justify-center sm:w-auto"
        >
          <Printer className="w-3.5 h-3.5" />
          Print / Export as PDF
        </button>
        <p className="text-[10px] text-muted-foreground/40 mt-1.5">Uses your browser's built-in Print dialog. Choose "Save as PDF" to download.</p>
      </div>
    </div>
  );
}

// ── Claim panel ───────────────────────────────────────────────────────────────

type ClaimState = "idle" | "open" | "submitting" | "done" | "error";

function ClaimPanel({ id }: { id: string }) {
  const claimToken = typeof window !== "undefined"
    ? localStorage.getItem(`sentinel_claim_${id}`) ?? ""
    : "";

  const [state, setState] = useState<ClaimState>("idle");
  const [email, setEmail] = useState("");
  const [errorMsg, setErrorMsg] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  // No claimToken = not the owner; don't show claim UI
  if (!claimToken) return null;

  if (state === "done") {
    return (
      <div className="surface-card rounded-xl p-5 flex items-center gap-3 border border-green-400/20">
        <Check className="w-4 h-4 text-green-400 shrink-0" />
        <div className="text-sm">
          <span className="text-foreground font-medium">Report saved.</span>{" "}
          <span className="text-muted-foreground">We'll email you when predictive alerts land.</span>
        </div>
      </div>
    );
  }

  if (state !== "open" && state !== "submitting") {
    return (
      <button
        onClick={() => { setState("open"); setTimeout(() => inputRef.current?.focus(), 50); }}
        className="w-full surface-card rounded-xl p-5 flex items-center justify-between gap-4 hover:border-primary/40 transition-all border border-border/60 text-left"
      >
        <div className="flex items-center gap-3">
          <Mail className="w-4 h-4 text-primary/60 shrink-0" />
          <div>
            <div className="text-sm font-medium text-foreground">Save this report to your account</div>
            <div className="text-xs text-muted-foreground mt-0.5">Get email alerts when predictive insights are ready.</div>
          </div>
        </div>
        <ChevronDown className="w-4 h-4 text-muted-foreground/40 shrink-0" />
      </button>
    );
  }

  const submit = async () => {
    if (!email.includes("@")) { setErrorMsg("Enter a valid email address."); return; }
    setState("submitting");
    setErrorMsg("");
    try {
      const res = await fetch(`/api/reports/${id}/claim`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ claimToken, email }),
      });
      if (res.ok) {
        setState("done");
      } else {
        const body = await res.json() as { error?: string };
        setErrorMsg(body.error ?? "Something went wrong.");
        setState("open");
      }
    } catch {
      setErrorMsg("Network error. Try again.");
      setState("open");
    }
  };

  return (
    <div className="surface-card rounded-xl p-5 border border-primary/20">
      <div className="flex items-center gap-2 mb-4">
        <Mail className="w-4 h-4 text-primary/60" />
        <span className="text-sm font-medium">Save this report</span>
      </div>
      <p className="text-xs text-muted-foreground mb-4 leading-relaxed">
        Enter your email and we'll link this report to your account — accessible from any device — and notify you when predictive health alerts are ready.
      </p>
      <div className="flex gap-2">
        <input
          ref={inputRef}
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && submit()}
          placeholder="you@example.com"
          disabled={state === "submitting"}
          className="flex-1 bg-background border border-border/60 rounded-lg px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/40 focus:outline-none focus:border-primary/60 disabled:opacity-50 transition-colors"
        />
        <button
          onClick={submit}
          disabled={state === "submitting" || !email}
          className="px-4 py-2 rounded-lg text-sm font-semibold text-background bg-primary hover:bg-primary/90 disabled:opacity-40 disabled:cursor-not-allowed transition-all shrink-0"
        >
          {state === "submitting" ? "Saving…" : "Save"}
        </button>
      </div>
      {errorMsg && <p className="text-xs text-red-400 mt-2">{errorMsg}</p>}
    </div>
  );
}



function ForecastChart() {
  const [scans, setScans] = useState(1);
  
  // Simulated data for the chart
  const data = [
    { month: "Jan", popBase: 95, popMin: 90, popMax: 100, personal: 96 },
    { month: "Feb", popBase: 92, popMin: 85, popMax: 98, personal: 94 },
    { month: "Mar", popBase: 88, popMin: 80, popMax: 95, personal: 89 },
    { month: "Apr", popBase: 85, popMin: 75, popMax: 92, personal: 87 },
    { month: "May", popBase: 81, popMin: 70, popMax: 90, personal: 84 },
    { month: "Jun", popBase: 78, popMin: 65, popMax: 88, personal: 80 },
    { month: "Jul", popBase: 74, popMin: 60, popMax: 85, personal: null },
    { month: "Aug", popBase: 70, popMin: 55, popMax: 82, personal: null },
    { month: "Sep", popBase: 66, popMin: 50, popMax: 78, personal: null },
    { month: "Oct", popBase: 62, popMin: 45, popMax: 75, personal: null },
    { month: "Nov", popBase: 58, popMin: 40, popMax: 72, personal: null },
    { month: "Dec", popBase: 54, popMin: 35, popMax: 68, personal: null },
  ];

  // We only show personal points up to the 'scans' count, and project the rest.
  const chartData = data.map((d, i) => {
    if (scans === 1) {
      return { ...d, personal: i === 4 ? d.personal : null }; // only 1 point at "May" (now)
    } else {
      // 5 scans: Jan to May
      if (i <= 4) return d;
      // Regression line for the rest
      const slope = -2.8; // derived
      const proj = 84 + slope * (i - 4);
      return { ...d, personalProj: proj };
    }
  });

  return (
    <div className="surface-card rounded-2xl p-6 border border-border/60 mb-6">
      <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
        <div>
          <h3 className="text-sm font-semibold text-foreground mb-1">Battery Degradation Model</h3>
          <motion.div 
            initial={{ width: 0 }} 
            animate={{ width: "100%" }} 
            transition={{ duration: 0.5, ease: "linear" }}
            className="overflow-hidden whitespace-nowrap"
          >
            <p className="text-xs text-muted-foreground">
              {scans === 1 ? "Industry baseline — 0 historical personal scans" : "Personal regression model — 5 historical scans"}
            </p>
          </motion.div>
        </div>
        <button 
          onClick={() => setScans(s => s === 1 ? 5 : 1)}
          className="px-3 py-1.5 rounded-lg text-xs font-medium border border-primary/30 text-primary hover:bg-primary/10 transition-colors"
        >
          Toggle Demo: {scans === 1 ? "Simulate returning user" : "Simulate new user"}
        </button>
      </div>

      <div className="h-64 w-full">
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
            <XAxis dataKey="month" stroke="#ffffff40" fontSize={10} tickMargin={10} />
            <YAxis domain={[0, 100]} stroke="#ffffff40" fontSize={10} />
            <Tooltip 
              contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', borderRadius: '8px', fontSize: '12px' }}
              itemStyle={{ color: '#e2e8f0' }}
            />
            <Legend wrapperStyle={{ fontSize: '12px' }} />
            
            <ReferenceArea x1="Sep" x2="Dec" fill="#ef4444" fillOpacity={0.1} />
            <ReferenceArea x1="Sep" x2="Dec" y1={100} y2={100} stroke="none" label={{ position: 'insideTop', value: 'Replacement Zone', fill: '#ef4444', fontSize: 10, opacity: 0.8 }} fill="none" />

            {/* Baseline Population Band (Confidence Interval) */}
            <Area 
              type="monotone" 
              dataKey="popMax" 
              stroke="none" 
              fill="#ffffff" 
              fillOpacity={0.03} 
              activeDot={false}
              name="Population Upper"
              legendType="none"
              tooltipType="none"
              isAnimationActive={true}
              animationDuration={800}
              animationEasing="ease-out"
            />
            <Area 
              type="monotone" 
              dataKey="popMin" 
              stroke="none" 
              fill="#000000" 
              fillOpacity={0.2} 
              activeDot={false}
              name="Population Lower"
              legendType="none"
              tooltipType="none"
              isAnimationActive={true}
              animationDuration={800}
              animationEasing="ease-out"
            />
            
            {/* Baseline Curve */}
            <Line 
              type="monotone" 
              dataKey="popBase" 
              stroke="#ffffff30" 
              strokeWidth={2} 
              dot={false} 
              name="Population Baseline" 
              strokeDasharray="5 5"
              isAnimationActive={true}
              animationDuration={1000}
              animationEasing="linear"
            />

            {/* Personal Scans */}
            <Line 
              type="monotone" 
              dataKey="personal" 
              stroke="#22d3ee" 
              strokeWidth={2} 
              dot={(props: any) => {
                if (props.value === null || props.value === undefined) return <></>;
                return (
                  <motion.circle
                    key={`dot-${props.index}`}
                    cx={props.cx}
                    cy={props.cy}
                    r={4}
                    fill="#22d3ee"
                    initial={{ scale: 0, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    transition={{ delay: 1.2 + props.index * 0.15, type: "spring", stiffness: 300, damping: 20 }}
                  />
                );
              }}
              activeDot={{ r: 6 }} 
              name="Your Scans" 
              isAnimationActive={true}
              animationDuration={1000}
              animationEasing="linear"
              animationBegin={200}
            />

            {/* Personal Projection */}
            {scans > 1 && (
              <Line 
                type="monotone" 
                dataKey="personalProj" 
                stroke="#22d3ee" 
                strokeWidth={2} 
                strokeDasharray="3 3"
                isAnimationActive={true}
                animationDuration={1000}
                animationEasing="linear"
                animationBegin={1200}
                dot={false} 
                name="Projected Trend" 
              />
            )}
          </ComposedChart>
        </ResponsiveContainer>
      </div>
      
      {scans > 1 && (
        <div className="mt-4 flex items-center justify-between text-xs border-t border-border/30 pt-4">
          <div className="text-muted-foreground">Confidence interval narrowed by 68% using local regression.</div>
          <div className="text-primary font-medium flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
            Next scan recommended: Jun 15
          </div>
        </div>
      )}
    </div>
  );
}

function ExpandableFinding({ f, style, icon, troubleshootKey }: {
  f: any; style: any; icon: React.ReactNode; troubleshootKey: string;
}) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`surface-card rounded-xl border-l-2 ${style.border} overflow-hidden`}>
      <button onClick={() => setOpen(o => !o)} className="w-full p-5 text-left flex items-start gap-3 hover:bg-muted/5 transition-colors">
        {icon}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-0.5 flex-wrap">
            <span className={`text-xs font-mono px-1.5 py-0.5 rounded border uppercase ${style.badge} shrink-0`}>{f.urgency}</span>
            <span className="text-xs font-mono text-muted-foreground/50">{f.component}</span>
          </div>
          <div className="text-sm font-semibold text-foreground">{f.title}</div>
          <p className="text-sm text-muted-foreground leading-relaxed mt-1">{f.body}</p>
        </div>
        <ChevronDown className={`w-4 h-4 text-muted-foreground/40 shrink-0 transition-transform duration-300 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div 
            initial={{ height: 0, opacity: 0, scaleY: 0, transformOrigin: "top" }}
            animate={{ height: "auto", opacity: 1, scaleY: 1 }}
            exit={{ height: 0, opacity: 0, scaleY: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 space-y-3 border-t border-border/30 pt-4">
          {f.oemContext && (
            <div className="rounded-lg bg-primary/5 border border-primary/15 px-4 py-3">
              <p className="text-xs font-mono text-primary/60 uppercase tracking-wide mb-1.5 flex items-center gap-1.5">
                <Shield className="w-3 h-3" /> Why OEM tools miss this
              </p>
              <p className="text-xs text-muted-foreground/80 leading-relaxed">{f.oemContext}</p>
              {f.caseStudyId && (
                <Link href={`/oem-failures#${f.caseStudyId}`} className="mt-2 inline-flex items-center gap-1 text-xs text-primary/70 hover:text-primary transition-colors">
                  See the real-world case study →
                </Link>
              )}
            </div>
          )}
          {troubleshootKey && (
            <Link href={`/troubleshoot?topic=${troubleshootKey}&title=${encodeURIComponent(f.title)}`} className="inline-flex items-center gap-2 text-xs font-semibold text-primary group relative">
              <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" /> Get step-by-step fix for this issue
              <div className="absolute -bottom-1 left-0 h-px bg-primary w-0 group-hover:w-full transition-all duration-200 ease-linear" />
            </Link>
          )}
        </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function ReproducibilityPanel({ result, combinedScoreVal }: { result: ReportResult; combinedScoreVal: number | null }) {
  const [open, setOpen] = useState(false);
  const weights: Record<string, number> = { Battery: 30, Thermals: 25, Storage: 25, Memory: 10, CPU: 10 };
  return (
    <div className="surface-card rounded-xl overflow-hidden border border-primary/20">
      <button onClick={() => setOpen(o => !o)} className="w-full flex items-center justify-between px-6 py-4 hover:bg-muted/5 transition-colors text-left">
        <div className="flex items-center gap-3">
          <Info className="w-4 h-4 text-primary/60" />
          <span className="text-sm font-semibold text-foreground">How this score was calculated</span>
          <span className="text-xs font-mono text-primary/50 border border-primary/20 bg-primary/5 px-2 py-0.5 rounded">v{result.algoVersion}</span>
        </div>
        <ChevronDown className={`w-4 h-4 text-muted-foreground/40 transition-transform duration-400 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div 
            initial={{ height: 0, opacity: 0, scaleY: 0, transformOrigin: "top" }}
            animate={{ height: "auto", opacity: 1, scaleY: 1 }}
            exit={{ height: 0, opacity: 0, scaleY: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="overflow-hidden"
          >
            <div className="border-t border-border/30 px-6 py-5 space-y-4">
              <p className="text-xs text-muted-foreground leading-relaxed">Each component is scored 0–100 using a deterministic formula, then weighted. The same inputs always produce the same output.</p>
          <div className="space-y-2">
            {result.components.map(c => {
              const w = weights[c.name] ?? 10;
              const contribution = Math.round(c.score * w / 100);
              return (
                <div key={c.name} className="rounded-lg bg-background/60 border border-border/40 px-4 py-3 font-mono text-xs">
                  <div className="flex justify-between mb-1">
                    <span className="text-foreground font-semibold">{c.name}</span>
                    <span className="text-muted-foreground">{c.score} × {w}% = <span className="text-primary font-bold">{contribution} pts</span></span>
                  </div>
                  <div className="text-muted-foreground/60">{c.detail}</div>
                </div>
              );
            })}
          </div>
          <div className="rounded-lg bg-primary/5 border border-primary/20 px-4 py-3 font-mono text-sm flex justify-between">
            <span className="text-muted-foreground">Hardware score</span>
            <span className="text-primary font-bold">{result.overall} / 100</span>
          </div>
          {combinedScoreVal !== null && (
            <div className="rounded-lg bg-primary/8 border border-primary/30 px-4 py-3 font-mono text-sm flex justify-between">
              <span className="text-muted-foreground">Combined (hardware 70% + habits 30%)</span>
              <span className="text-primary font-bold">{combinedScoreVal} / 100</span>
            </div>
          )}
          <Link href="/scoring" className="inline-flex items-center gap-1.5 text-xs text-primary/70 hover:text-primary transition-colors">
            Read the full scoring methodology <ArrowRight className="w-3 h-3" />
          </Link>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function Report() {
  const params = useParams<{ id: string }>();
  const [result, setResult] = useState<ReportResult | null>(null);
  const [habitScore, setHabitScore] = useState<number | null>(null);
  const [combinedScoreVal, setCombinedScoreVal] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loadedFrom, setLoadedFrom] = useState<"server" | "local" | null>(null);
  const [, navigate] = useLocation();
  const [showBanner, setShowBanner] = useState(true);

  useEffect(() => {
    if (result?.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0) {
      const timer = setTimeout(() => setShowBanner(false), 5000);
      return () => clearTimeout(timer);
    }
    return undefined;
  }, [result]);

  useEffect(() => {
    const id = params?.id;
    if (!id) { setError("No report ID provided."); return; }

    // Intercept claim token from URL if present (Direct Upload flow)
    const searchParams = new URLSearchParams(window.location.search);
    const urlClaimToken = searchParams.get("claim");
    if (urlClaimToken) {
      try {
        localStorage.setItem(`sentinel_claim_${id}`, urlClaimToken);
        // Clean URL to prevent accidental sharing of the claim token
        const cleanUrl = window.location.pathname;
        window.history.replaceState({}, document.title, cleanUrl);
      } catch (e) {
        console.error("Failed to save claim token", e);
      }
    }

    fetch(`/api/reports/${id}`)
      .then(async (res) => {
        if (res.ok) {
          const body = await res.json() as { result: ReportResult; habitScore: number | null; combinedScore: number | null };
          setResult(body.result);
          setHabitScore(body.habitScore);
          setCombinedScoreVal(body.combinedScore);
          setLoadedFrom("server");
          injectReportOG(body.result);
          return;
        }
        if (res.status === 404) {
          loadFromLocalStorage(id);
          // Opportunistic upload for legacy local IDs
          const stored = localStorage.getItem(`sentinel_report_${id}`);
          if (stored) {
            try {
              fetch("/api/reports", {
                method: "POST",
                headers: { "Content-Type": "application/json", "Idempotency-Key": `legacy-${id}` },
                body: JSON.stringify({ rawJson: JSON.parse(stored), legacy: true }),
              })
                .then(async (upRes) => {
                  if (upRes.ok) {
                    const { id: newId } = await upRes.json() as { id: string };
                    navigate(`/r/${newId}`);
                  }
                })
                .catch(() => {});
            } catch (e) { console.error("Legacy upload failed", e); }
          }
          return;
        }
        loadFromLocalStorage(id);
      })
      .catch(() => loadFromLocalStorage(id));
   
  }, [params?.id]);

  function loadFromLocalStorage(id: string) {
    const stored = localStorage.getItem(`sentinel_report_${id}`);
    if (!stored) {
      setError("Report not found. Reports are stored locally — this link only works on the device that generated it.");
      return;
    }
    try {
      const raw = JSON.parse(stored);
      const parsed = SentinelReportSchema.safeParse(raw);
      if (!parsed.success) { setError("Report data is corrupted or outdated."); return; }
      const r = generateReport(parsed.data);
      setResult(r);
      setLoadedFrom("local");
      injectReportOG(r);
    } catch {
      setError("Could not load report data.");
    }
  }

  if (error) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center px-6">
        <div className="max-w-md text-center">
          <Shield className="w-10 h-10 text-muted-foreground/30 mx-auto mb-4" />
          <h2 className="text-lg font-semibold mb-2">Report not found</h2>
          <p className="text-sm text-muted-foreground mb-6 leading-relaxed">{error}</p>
          <Link href="/health-test" className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-background bg-primary glow-cyan">
            Generate a new report <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-sm text-muted-foreground font-mono animate-pulse">Loading report…</div>
      </div>
    );
  }

  const id = params?.id ?? "";
  const urgencyOrder = { critical: 0, warning: 1, info: 2 } as const;
  const publicFindings = result.findings.filter((f) => !f.pro).sort((a, b) => urgencyOrder[a.urgency] - urgencyOrder[b.urgency]);
  const proFindings    = result.findings.filter((f) => f.pro);
  const genDate = new Date(result.generatedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  return (
    <div className="min-h-screen bg-background text-foreground report-printable">
      <AnimatePresence>
        {result?.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0 && showBanner && (
          <motion.div 
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -20, opacity: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="w-full border-b border-red-500/40 bg-red-500/10 px-6 py-3"
          >
            <div className="max-w-3xl mx-auto flex items-center gap-3">
              <AlertTriangle className="w-4 h-4 text-red-400 shrink-0" />
              <div>
                <span className="text-xs font-bold text-red-400 uppercase tracking-wider">Data Collection Notes · </span>
                <span className="text-xs text-red-400/80">{result.dataQuality.structuredWarnings.map((w: any) => w.title).join(" · ")} — some telemetry was excluded from scoring.</span>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      {loadedFrom === "local" && (
        <div className="w-full bg-amber-500 text-amber-950 px-6 py-4 flex items-center justify-center gap-3 shadow-md z-50 relative">
          <AlertTriangle className="w-5 h-5 shrink-0" />
          <p className="text-sm font-bold">
            This report was scored offline and has not been verified by Sentinel servers. Scores may differ from the server-computed result.
          </p>
        </div>
      )}

      {/* Report header */}
      <div className="border-b border-border/60 bg-card/20 px-6 py-5">
        <AnimateIn>
          <div className="max-w-3xl mx-auto flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center">
                <Shield className="w-4 h-4 text-primary" />
              </div>
              <div>
                <div className="text-xs font-mono text-muted-foreground/60 uppercase tracking-wide">Sentinel Hardware Report</div>
                <div className="text-sm font-semibold">{result.system.model}</div>
              </div>
            </div>
            <div className="flex items-center gap-3">
              {loadedFrom === "server" && (
                <span className="text-xs font-mono text-green-400/60 border border-green-400/20 bg-green-400/5 px-2 py-0.5 rounded-full">
                  synced
                </span>
              )}
              <div className="text-xs font-mono text-muted-foreground/50">{genDate}</div>
            </div>
          </div>
        </AnimateIn>
      </div>

      <div className="px-6 py-12">
        <div className="max-w-3xl mx-auto space-y-8">

          {/* Overall score */}
          <AnimateIn>
            <div className="surface-card rounded-2xl p-8">
              <div className="flex items-center gap-8 flex-wrap">
                <div className="relative shrink-0">
                  <ScoreRing score={combinedScoreVal ?? result.overall} />
                  <div className="absolute inset-0 flex flex-col items-center justify-center">
                    <div className="text-2xl font-bold tabular-nums">{combinedScoreVal ?? result.overall}</div>
                    <div className="text-xs text-muted-foreground">/100</div>
                  </div>
                </div>
                <div className="flex-1">
                  <div className="text-2xl font-bold mb-1 flex items-center gap-3">
                    {result.grade} — {result.gradeLabel}
                    {loadedFrom === "local" && (
                      <span className="text-xs font-mono text-amber-500 border border-amber-500/30 bg-amber-500/10 px-2 py-0.5 rounded-full font-normal tracking-wide flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" /> unverified
                      </span>
                    )}
                  </div>
                  {combinedScoreVal !== null && (
                    <div className="flex items-center gap-3 mb-3 text-xs font-mono">
                      <span className="text-muted-foreground/60">Hardware</span>
                      <span className="text-foreground">{result.overall}</span>
                      <span className="text-muted-foreground/40">+</span>
                      <span className="text-muted-foreground/60">Habits</span>
                      <span className="text-accent">{habitScore}</span>
                      <span className="text-muted-foreground/40">→</span>
                      <span className="text-primary font-semibold">Combined {combinedScoreVal}</span>
                    </div>
                  )}
                  <div className="text-sm text-muted-foreground mb-4 leading-relaxed">
                    {(combinedScoreVal ?? result.overall) >= 80
                      ? "Your hardware is in good shape. A few items to watch."
                      : (combinedScoreVal ?? result.overall) >= 60
                      ? "Some components need attention. Review the findings below."
                      : "Multiple components are degraded. Prioritise the critical findings."}
                  </div>
                  <div className="flex flex-wrap gap-2 text-xs">
                    <span className="text-red-400/80 bg-red-400/5 border border-red-400/20 px-2 py-0.5 rounded-full font-mono">
                      {publicFindings.filter((f) => f.urgency === "critical").length} critical
                    </span>
                    <span className="text-amber-400/80 bg-amber-400/5 border border-amber-400/20 px-2 py-0.5 rounded-full font-mono">
                      {publicFindings.filter((f) => f.urgency === "warning").length} warnings
                    </span>
                    <span className="text-cyan-400/80 bg-cyan-400/5 border border-cyan-400/20 px-2 py-0.5 rounded-full font-mono">
                      {publicFindings.filter((f) => f.urgency === "info").length} healthy
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </AnimateIn>

          {/* ── Data Quality Transparency Banners ───────────────────────── */}
          {result.dataQuality?.structuredWarnings && result.dataQuality.structuredWarnings.length > 0 && (
            <AnimateIn delay={0.04}>
              <div className="space-y-3">
                {result.dataQuality.structuredWarnings.map((w, i) => {
                  const isHigh = w.severity === "high";
                  return (
                    <div
                      key={i}
                      className={`rounded-xl border overflow-hidden ${
                        isHigh
                          ? "border-amber-500/40 bg-amber-500/8"
                          : "border-amber-500/20 bg-amber-500/5"
                      }`}
                    >
                      {/* Banner header */}
                      <div className={`px-5 py-3 flex items-center gap-3 ${
                        isHigh ? "bg-amber-500/15 border-b border-amber-500/20" : "border-b border-amber-500/10"
                      }`}>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                          isHigh ? "bg-amber-500/20" : "bg-amber-500/10"
                        }`}>
                          <AlertTriangle className={`w-4 h-4 ${isHigh ? "text-amber-400" : "text-amber-500/70"}`} />
                        </div>
                        <div className="flex-1">
                          <h3 className={`text-sm font-bold ${isHigh ? "text-amber-400" : "text-amber-500/80"}`}>
                            {w.title}
                          </h3>
                          {w.excludedFromScoring && (
                            <span className="text-xs font-mono text-amber-500/50 mt-0.5 block">
                              EXCLUDED FROM OVERALL SCORE
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Banner body */}
                      <div className="px-5 py-4 space-y-3">
                        <p className="text-sm text-muted-foreground leading-relaxed">{w.detail}</p>
                        {w.oemComparison && (
                          <div className="rounded-lg bg-background/60 border border-border/40 px-4 py-3">
                            <p className="text-xs font-mono text-muted-foreground/50 uppercase tracking-wide mb-1.5">
                              vs. OEM tools
                            </p>
                            <p className="text-xs text-muted-foreground/80 leading-relaxed">{w.oemComparison}</p>
                          </div>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Legacy fallback: plain-text data quality warnings (only if no structured ones) */}
          {(!result.dataQuality?.structuredWarnings || result.dataQuality.structuredWarnings.length === 0) &&
            result.dataQuality?.warnings && result.dataQuality.warnings.length > 0 && (
            <AnimateIn delay={0.04}>
              <div className="surface-card rounded-xl p-5 border border-amber-500/20 bg-amber-500/5">
                <div className="flex items-center gap-3 mb-3">
                  <Info className="w-4 h-4 text-amber-500" />
                  <h2 className="text-sm font-bold text-amber-500 uppercase tracking-wider">Data Collection Notes</h2>
                </div>
                <ul className="space-y-2">
                  {result.dataQuality.warnings.map((w: string, i: number) => (
                    <li key={i} className="text-sm text-amber-500/80 list-disc list-inside">{w}</li>
                  ))}
                </ul>
              </div>
            </AnimateIn>
          )}

          {/* Component breakdown — staggered animated */}
          <div className="surface-card rounded-2xl p-7">
            <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest mb-6">Component breakdown</h2>
            <div className="space-y-6">
              {result.components.map((c, idx) => {
                const s = STATUS_STYLES[c.status];
                const INTERP: Record<string, string> = {
                  Battery: c.score >= 80 ? "Battery is healthy." : c.score >= 60 ? `Your battery retains ${c.score}% effective capacity — adequate but declining.` : `Battery severely degraded at ${c.score}% — plan replacement soon.`,
                  Thermals: c.score >= 80 ? "Cooling system is performing well." : c.score >= 60 ? "Temperatures are elevated — consider cleaning vents." : "Critical heat levels — thermal paste may need replacement.",
                  Storage: c.score >= 80 ? "Drive health and free space are in good condition." : c.score >= 60 ? "Storage showing wear — monitor closely." : "Critical drive wear or low space — back up now.",
                  Memory: c.score >= 80 ? "Memory usage is healthy." : c.score >= 60 ? "Memory usage moderately high." : "System under memory pressure — expect slowdowns.",
                  CPU: c.score >= 80 ? "CPU load is healthy with no throttling." : c.score >= 60 ? "Some CPU throttling detected." : "Significant throttling is impacting performance.",
                };
                const scoreColor = c.score >= 80 ? "#22d3ee" : c.score >= 60 ? "#f59e0b" : "#f87171";
                return (
                  <motion.div key={c.name} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 + idx * 0.1, duration: 0.4, ease: [0.25, 0.1, 0.25, 1] }}>
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-semibold text-foreground">{c.name}</span>
                        <span className={`text-xs px-1.5 py-0.5 rounded border ${s.badge} font-mono`}>{c.status}</span>
                      </div>
                      <span className="text-lg font-bold font-mono tabular-nums" style={{ color: scoreColor }}>{c.score}</span>
                    </div>
                    <div className="h-2 bg-border/20 rounded-full overflow-hidden mb-2">
                      <motion.div className={`h-full rounded-full ${s.bar}`} initial={{ width: 0 }} animate={{ width: `${c.score}%` }} transition={{ delay: 0.2 + idx * 0.15, duration: 0.8, ease: "easeOut" }} />
                    </div>
                    <p className="text-xs text-muted-foreground leading-relaxed">{INTERP[c.name] ?? c.detail}</p>
                    <p className="text-xs text-muted-foreground/40 font-mono mt-0.5">{c.detail}</p>
                  </motion.div>
                );
              })}
            </div>
          </div>

          {/* ── Health Forecast Timeline ────────────────────────────────────── */}
          {result.predictions && result.predictions.length > 0 && (
            <AnimateIn delay={0.06}>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Health Forecast Timeline</h2>
                  <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-primary/10 border border-primary/30 text-primary flex items-center gap-1">
                    <Clock className="w-3 h-3" /> FORECAST
                  </span>
                </div>
                <p className="text-xs text-muted-foreground/50 leading-relaxed -mt-1 mb-1">
                  How long before each component becomes a problem — based on current readings and degradation curves.
                </p>
                <ForecastChart />
                {result.predictions.map((pred, i) => {
                  const severityStyles = {
                    stable: {
                      border: "border-l-green-400",
                      icon: <CheckCircle2 className="w-4 h-4 text-green-400" />,
                      badge: "text-green-400 bg-green-400/8 border-green-400/20",
                      badgeLabel: "Stable",
                      glow: "bg-green-400",
                    },
                    declining: {
                      border: "border-l-amber-400",
                      icon: <TrendingDown className="w-4 h-4 text-amber-400" />,
                      badge: "text-amber-400 bg-amber-400/8 border-amber-400/20",
                      badgeLabel: "Declining",
                      glow: "bg-amber-400",
                    },
                    urgent: {
                      border: "border-l-red-400",
                      icon: <AlertTriangle className="w-4 h-4 text-red-400" />,
                      badge: "text-red-400 bg-red-400/8 border-red-400/20",
                      badgeLabel: "Urgent",
                      glow: "bg-red-400",
                    },
                  };
                  const s = severityStyles[pred.severity];
                  return (
                    <div key={i} className={`surface-card rounded-xl p-5 border-l-2 ${s.border}`}>
                      <div className="flex items-start justify-between gap-4 mb-3">
                        <div className="flex items-center gap-3">
                          {s.icon}
                          <div>
                            <div className="text-sm font-semibold text-foreground">{pred.component}</div>
                            <div className="text-xs font-mono text-muted-foreground/50 mt-0.5">{pred.currentValue}</div>
                          </div>
                        </div>
                        <span className={`text-xs font-mono px-2 py-0.5 rounded-full border shrink-0 ${s.badge}`}>
                          {s.badgeLabel}
                        </span>
                      </div>
                      {/* Timeline bar */}
                      <div className="rounded-lg bg-muted/10 border border-border/30 px-4 py-3 mb-3">
                        <div className="flex items-center gap-2 mb-1">
                          <Clock className="w-3 h-3 text-muted-foreground/40" />
                          <span className="text-xs font-mono text-muted-foreground/50 uppercase tracking-wide">Projected Timeline</span>
                        </div>
                        <div className="flex items-center gap-3">
                          <div className={`w-2 h-2 rounded-full ${s.glow} animate-glow-pulse shrink-0`} />
                          <span className="text-sm font-medium text-foreground">{pred.projectedTimeline}</span>
                        </div>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">{pred.insight}</p>
                    </div>
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Public findings — expandable */}
          {publicFindings.length > 0 && (
            <AnimateIn delay={0.07}>
              <div className="space-y-3">
                <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Findings</h2>
                {publicFindings.map((f, i) => {
                  const style = URGENCY_STYLES[f.urgency];
                  const dot = f.urgency === "critical" ? "bg-red-400" : f.urgency === "warning" ? "bg-amber-400" : "bg-cyan-400";
                  const tk: Record<string, string> = { Battery: "battery", Thermals: "thermal", Storage: "storage", Memory: "memory", CPU: "cpu" };
                  return (
                    <ExpandableFinding key={i} f={f} style={style} icon={<span className={`w-2 h-2 rounded-full ${dot} shrink-0 mt-2`} />} troubleshootKey={tk[f.component] ?? ""} />
                  );
                })}
              </div>
            </AnimateIn>
          )}

          {/* Pro findings (blurred) */}
          {proFindings.length > 0 && (
            <AnimateIn delay={0.08}>
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-mono text-muted-foreground/60 uppercase tracking-widest">Diagnostic findings</h2>
                  <span className="text-xs font-mono px-2 py-0.5 rounded-full bg-accent/10 border border-accent/30 text-accent">PRO</span>
                </div>
                {proFindings.map((f, i) => (
                  <div key={i} className="surface-card rounded-xl p-5 border border-accent/20 relative overflow-hidden">
                    <div className="absolute inset-0 backdrop-blur-sm bg-background/60 z-10 flex items-center justify-center rounded-xl">
                      <div className="text-center px-6">
                        <Lock className="w-5 h-5 text-accent mx-auto mb-2" />
                        <div className="text-sm font-semibold text-foreground mb-1">Pro finding</div>
                        <div className="text-xs text-muted-foreground mb-3">Pro diagnostic findings unlock with early access.</div>
                        <Link href="/waitlist" className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold text-background bg-accent hover:bg-accent/90 transition-all">
                          Get early access <ArrowRight className="w-3 h-3" />
                        </Link>
                      </div>
                    </div>
                    <div className="opacity-20 select-none pointer-events-none" aria-hidden>
                      <div className="text-xs font-mono text-muted-foreground/50 mb-1">{f.component}</div>
                      <div className="text-sm font-semibold mb-2">{f.title}</div>
                      <p className="text-sm text-muted-foreground">{f.body}</p>
                    </div>
                  </div>
                ))}
              </div>
            </AnimateIn>
          )}

          {/* Score Reproducibility Panel */}
          <AnimateIn delay={0.075}>
            <ReproducibilityPanel result={result} combinedScoreVal={combinedScoreVal} />
          </AnimateIn>

          {/* Claim panel (only shown when user owns the report) */}
          <AnimateIn delay={0.06}>
            <ClaimPanel id={id} />
          </AnimateIn>

          {/* Share row */}
          <AnimateIn delay={0.07}>
            <SharePanel id={id} isLocal={loadedFrom === "local"} />
          </AnimateIn>

          {/* Footer */}
          <AnimateIn delay={0.08}>
            <div className="surface-card rounded-xl p-5 space-y-3">
              <div className="flex items-center justify-between flex-wrap gap-4">
                <div className="text-xs text-muted-foreground/60 leading-relaxed max-w-sm">
                  {loadedFrom === "server"
                    ? "This report is stored on Sentinel's servers and accessible from any device via the link above."
                    : "This report was generated from your device's hardware telemetry."}
                </div>
                <Link
                  href="/health-test"
                  className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg text-xs font-semibold border border-border/60 text-foreground hover:border-primary/60 hover:text-primary transition-all"
                >
                  Run another scan <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
              <div className="border-t border-border/30 pt-3 flex items-center justify-between flex-wrap gap-2">
                <span className="text-xs font-mono text-muted-foreground/40">
                  Algorithm v{result.algoVersion} · {genDate}
                </span>
                <Link
                  href="/changelog"
                  className="text-xs text-primary/60 hover:text-primary transition-colors flex items-center gap-1"
                >
                  Scoring methodology & changelog <ArrowRight className="w-3 h-3" />
                </Link>
              </div>
            </div>
          </AnimateIn>

        </div>
      </div>
    </div>
  );
}
